### ISSUE TITLE
[API] Remove `parax.grad` and `@layer_construction` markers and replace them with a monkey patch of `jax.grad`

### ISSUE THREAD

**Issue by zhuohan123** [alpa-projects/alpa#288]
Besides `@parallelize` decorator, in current parax, we have the following decorators that need to be stated by the user:

1. Replace `jax.grad` by `parax.grad`.
2.`@manual_layer_construction` or `@automatic_layer_construction`.

Code example:
```python
@parallelize
def f(...):
  @automatic_layer_construction
  def loss_func():
    # network body
    ...
  grad = parax.grad(loss_func)
  # apply grad
  ...
  return new_weights
```

I'm thinking about the removing these two extra decorators. By removing these two decorators, a user only need to add the `@parallelize` decorator to any jax training function to make it model parallel. This provides a much nicer API:

```python
@parallelize
def f(...):
  # basically now f can be any normal jax training step function
  def loss_func():
    # network body
    ...
  loss = loss_func()
  grad = jax.grad(loss)
  # apply grad
  ...
  return new_weights
```

The exact modification is as the following:

1. Use a monkey patch of `jax.grad` to implement the function of `parax.grad`. With the monkey patch, `jax.grad` will behave like `parax.grad` when it is being traced in a `@parallelize` decorator. We will set some environment variables in the `@parallelize` decorator.
   ```python
   def new_grad(*args):
     if in_parallelize:
       return parax.grad(*args)
     else:
       return jax.grad(*args)
 
   jax.grad = new_grad
   ```
2. For `@layer_constuction` decorators, we can move them into the new `jax.grad`:
   ```python
   def new_grad(f, *args):
     if in_parallelize:
       if auto_layer:
         f = auto_layer_construction(f)
       elif manual_layer:
         f = manual_layer_construction(f)
       return parax.grad(f, *args)
     else:
       return jax.grad(f, *args)
 
   jax.grad = new_grad
   ```

Some potential downsides of this modification:
1. We will not be able to stack `@parallelize` with other decorators. For example, the following code will not work after the modification:
   ```python
   @parallelize
   @jax.jit
   def f(...):
     ...
   ```
2. We need to carefully deal with nested `jax.grad`.
3. What if the input workload is a pipelined inference workload?

How do you feel about this @merrymercy @zhisbug?

**Comment by merrymercy** [comment]
https://github.com/alpa-projects/alpa/pull/565
