### ISSUE TITLE
[BUG] grpc timeout occurs when computation cost is high

### ISSUE THREAD

**Issue by TarzanZhao** [alpa-projects/alpa#347]
I get "grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: status = StatusCode.DEADLINE_EXCEEDED" when scaleing up the model size or batch size. 

<img width="525" alt="image" src="https://user-images.githubusercontent.com/45677459/156139707-c52d1e4d-bd19-4bf8-a647-dbaa35204a82.png">

I find this problem occurs during Alpa runs shard_each_stage with pipeline_distributed_compile and comes down to this line of Ray code: [https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/monitor.py#L271](url). The code is used to fetch some information(like memory usage) for demonstration purpose which should not take too much time. 

I fix it by increasing the timeout constant 60 or just bypassing the whole method. I try changing some Alpa global config variable and It seems the problem has nothing to do with Alpa. But I still don't think hacking into Ray code is a good idea to solve this problem.

**Comment by zhisbug** [comment]
I have reproduced this issue after using the A100 cluster

**Comment by merrymercy** [comment]
Closed due to inactivity
