### ISSUE TITLE
[PERF] Handling cases like (2, 1024, ...) when chunks = 4 in local allgather

### ISSUE THREAD

**Issue by zhisbug** [alpa-projects/alpa#350]
In cross mesh resharding, instead of rewriting the sharding spec to let the split happen solely on second dim `1024`, which would be very slow for communication, we should let the split happen first on both the first dim `2` and the rest on the second dim.

**Comment by ZYHowell** [comment]
https://github.com/alpa-projects/alpa/pull/356 Implements the algo discussed above. For further enhancement, see https://github.com/alpa-projects/alpa/issues/416.
