### ISSUE TITLE
[PERF] Port fused softmax, fused GELU etc into Alpa

### ISSUE THREAD

**Issue by zhisbug** [alpa-projects/alpa#351]
It is worth porting the manually optimized fused kernel (https://github.com/NVIDIA/Megatron-LM/tree/main/megatron/fused_kernels) from Megatron-LM into Alpa.
They seem to increase 3- 8 TFLOPS on GPT-3 based on my observations.

**Comment by merrymercy** [comment]
Merged into https://github.com/alpa-projects/alpa/issues/406
