### ISSUE TITLE
[RUNTIME] Refactor DeviceCluster, DeviceMesh, and MeshHostWorker classes to support distributed inference

### ISSUE THREAD

**Issue by zhuohan123** [alpa-projects/alpa#353]
In our current codebase, `DeviceCluster`, `VirtualPhysicalMesh`, `PhysicalDeviceMesh`, and `MeshHostWorker` have the relationship as in the following diagram:

![Mesh_Worker Refactor](https://user-images.githubusercontent.com/17310766/156325194-01d68272-e4b7-4e09-9bb7-f59c96668c6c.png)

I would like to modify it to the following diagram to support distributed inference:

![Mesh_Worker Refactor (4)](https://user-images.githubusercontent.com/17310766/156328269-06e560ce-f122-48b4-9147-a628ba05779d.png)
Some major differences:

1. Each `MeshHostWorker` manages one and only one GPU.
2. `MeshHostWorker` is directly managed by `DeviceCluster` instead of by `PhysicalDeviceMesh`.
3. `PhysicalMesh` only stores the pointer to `MeshHostWorker` instead of owning it. Because of this, we don't need to distinguish between the virtual and non-virtual physical mesh. In addition, multiple `PhysicalMesh` can point to the same `MeshHostWorker`.

Pros:

1. Support running multiple computation graphs with different pipeline slicing. Especially important for inference.
2. Each GPU has its own actor, might be faster.
3. Minimal code change. Current `PhysicalDeviceMesh` already support multiple `MeshHostWorker`. Don't require code change on resharding side.

Cons:

1. More ray actors, more control messages on Ray. Might hurt performance. (Can be optimized by making PhysicalDeviceMesh a ray actor).
2. There are places in the code that we assume each `MeshHostWorker` corresponds to a node (e.g. [here]( https://github.com/alpa-projects/alpa/blob/main/alpa/pipeline_parallel/cross_mesh_resharding.py#L476-L498)). Need code change here.

**Comment by zhuohan123** [comment]
> This change might have a big impact on how NCCL collectives between GPUs are called; e.g. allgather currently uses a CUPY API that assumes a process has multiple GPUs; There are many other nccl calls in cross-mesh resharding that need to be changed.

I feel like we don't need that much code change after reading through the code. Our current architecture already supports one `PhysicalMesh` pointing to multiple `MeshHostWorker`. We only need to pass in one GPU for all multi-GPU APIs. My only concern is on some places in the code where we do assume each `MeshHostWorker` corresponds to a single node (e.g. in local all-gather).

> Yes, and we might also need to test which type of collectives will be faster: type 1: 4x4 clusters, 16 ranks, 4 processes, each process own 4 ranks (gpus); do send/recv call between two rank, or collective calls among 16 ranks type 2: 4x4 clusters, 16 ranks, 16 processes, each process own 1 rank (GPU);

In the end, the collective communication started by NCCL should be exactly the same before and after the refactoring. I am more worried about the additional control overhead brought by more Ray actors.

**Comment by zhuohan123** [comment]
Hao's comment: `allgather_communicators` in `MeshHostWorker` currently do all-gather optimization on all devices in a single `MeshHostWorker`. Need to be modified with this change.

**Comment by zhuohan123** [comment]
Turn out one major blocker of this proposal is within a single `PhysicalDeviceMesh`: 

- All the workers in a device mesh need to connect to the same XLA's `distributed_runtime_service`. 
- A worker's XLA backend is created from the `distributed_runtime_client`.
- All the XLA programs and tensors belong to an XLA backend.
- Tensors belonging to one backend cannot be directly used by another backend without copying.

This means:

- If two `PhysicalDeviceMesh` point to one `MeshHostWorker`, the `MeshHostWorker` needs to maintain two `distributed_runtime_client` and two backends. These two backends behave like they are on two separate GPUs. They will fight for GPU memory. A tensor can be seen by only one device mesh. 
- Our original goal for the refactor is to run the inference graph on a different set of `PhysicalDeviceMesh` than the training graph while sharing the parameters. However, with this blocker, this goal becomes impossible to reach.

Our potential outs:

- @merrymercy Investigate slicing device meshes in XLA. More specifically, we only create one huge `distributed_runtime_service` for the whole device cluster and then compile programs that only use a subset of devices from the `distributed_runtime_service`. This might not be possible since in the SPMD pass there might be assumptions that a program has to use all the devices in the graph. Also we might have to execute a program on all devices even when the program only requires a subset of devices.
- @zhuohan123 At the same time, start to implement inference on top of our original runtime. Let the runtime support multiple programs.

**Comment by zhuohan123** [comment]
1. Only one distributed runtime service (i.e. 32 GPUs connect to a single runtime service and compile a program only using 16, 17, 18, 19 GPU).
2. Still start multiple runtime services, but share the memory allocator.

**Comment by ZYHowell** [comment]
For 2, [Backend's init](https://github.com/alpa-projects/tensorflow-alpa/blob/b1393d3e8844e8594853306b591626e33b565beb/tensorflow/compiler/xla/service/backend.cc#L132-L133) may help.

**Comment by zhuohan123** [comment]
#375 implements inference on top of our original runtime.

**Comment by scv119** [comment]
I'll try to give this a shot.

**Comment by zhuohan123** [comment]
@scv119 Great to see you are interested! We can chat before you actually start implementing this.

**Comment by zhuohan123** [comment]
This issue is blocked by dependency on XLA's distributed runtime. More specifically right now each device mesh needs its own XLA runtime, making sharing tensors and managing memory across different meshes hard. Close this issue temporarily to reduce confusion.

**Comment by merrymercy** [comment]
The ultimate goal is to enable one process (actor) per GPU. There are two methods.

- Method 1: A single distributed XLA server.
    To implement this, we need to enable compile and launch XLA shared SPMD executables on given devices not the whole mesh.
- Method 2: Multiple distributed XLA servers. One server per device mesh
    To implement this, we can decouple the real GPU backend and distributed client.
