### ISSUE TITLE
[FEATURE] Investegate GlobalDeviceArray and Maybe Implement DistributedArray with it

### ISSUE THREAD

**Issue by zhuohan123** [alpa-projects/alpa#357]
[GlobalDistributedArray](https://github.com/google/jax/blob/main/jax/experimental/global_device_array.py) is an experimental feature in Jax that is used to manage sharded array in multi-process Jax. It supports [serialization/deserialization](https://github.com/google/jax/tree/main/jax/experimental/gda_serialization) of sharded array. We can use this class for model saving/loading and maybe weight initialization.

**Comment by merrymercy** [comment]
It cannot be directly used because it only supports one mesh, but we can learn some thing from it can port the serialization/deserialization to our DistributedArray

**Comment by zhuohan123** [comment]
My thought is to use it in `DistributedArray` instead of replacing `DistributedArray` with it. Because for model saving/loading, if we don't use `GlobalDeviceArray`, we need to reimplement the serialization/deserialization of a shared array.

**Comment by merrymercy** [comment]
Its serialization support is trivial. It does not provide a flexible solution for serialization.

**Comment by zhuohan123** [comment]
Let me double-check this. From what I heard this thing should be able to support loading to a sharded tensor from another sharded tensor with a different sharding strategy.

**Comment by merrymercy** [comment]
Sorry, I skipped the `gda_serialization` folder. You are right. It utilizes [tensorestore](https://github.com/google/tensorstore) and google cloud storage as the network file system to gather the results.

**Comment by PKUFlyingPig** [comment]
I did some experiments on AWS. The tensorstore package supports different sharding specs between loading and saving. I think we can utilize this package and integrate it into DistributedArray class. I may initiate a PR if I successfully save/load the DistributedArray with tensorstore.

**Comment by merrymercy** [comment]
Finished by https://github.com/alpa-projects/alpa/pull/487
