### ISSUE TITLE
[BUG] broadcast_in_dim + concatenate causes segfault

### ISSUE THREAD

**Issue by yf225** [alpa-projects/alpa#371]
I was trying to do `broadcast_in_dim` + `concatenate` but got a segfault:
```python
import jax
import alpa

class_token = jax.numpy.empty((1, 1, 768))
x = jax.numpy.empty((196, 8, 768))

def jax_func(class_token, x):
	class_token = jax.lax.broadcast_in_dim(class_token, [1, 8, 768], [0, 1, 2])
	x = jax.lax.concatenate([class_token, x], 0)
	return x

alpa_output = alpa.api.parallelize(jax_func)(class_token, x)
```
Output:
```
free(): invalid next size (fast)
Aborted (core dumped)
```
It also seems that if I swap the order of `class_token` and `x` in the call to `jax.lax.concatenate()` (i.e. doing `x = jax.lax.concatenate([x, class_token], 0)` instead), it will work fine. Maybe in the code we expect the first argument of `jax.lax.concatenate()` to be contiguous?

**Comment by merrymercy** [comment]
This bug has been fixed by this PR https://github.com/alpa-projects/tensorflow-alpa/pull/99
