### ISSUE TITLE
A small question on the early pruning in dp

### ISSUE THREAD

**Issue by walkerning** [alpa-projects/alpa#385]
Hi, thanks for open sourcing this great project.
I'm reading the code currently, and has a very small question:
Maybe, this `last_max_stage_cost` [here](https://github.com/alpa-projects/alpa/blob/main/alpa/pipeline_parallel/stage_construction.py#L133) need to be updated to `max_stage_cost` in the last direction?

**Comment by zhuohan123** [comment]
Thanks for filing the issue! It is actually a bug and fixed in #389
