### ISSUE TITLE
[QUESTION] Two code questions

### ISSUE THREAD

**Issue by kevinsouthxu** [alpa-projects/alpa#399]
question 1:
At alpa/alpa/shard_parallel/auto_sharding.py line760-774, what does the (h) constraints mean?
https://github.com/alpa-projects/alpa/blob/2945fc4ea29e16ba7014e165e85624ed6d12b137/alpa/shard_parallel/auto_sharding.py#L760
```
    alias_set = set()
    for (idx, (i, j)) in enumerate(A):
        R = len(s[i])
        C = len(s[j])
        if (i, j) in alias_set:
            raise ValueError(f"Duplicated edges: {(i, j)}")

        alias_set.add((i, j))
        alias_set.add((j, i))

        for row in range(len(s[i])):
            for col in range(len(s[j])):
                if v[idx][row * C + col] > 0.5:
                    prob += s[i][row] + s[j][col] <= 1
```
question 2:
At alpa/playground/auto_sharding_solver/hlo.py line342
In Alpa's paper, the computation time is set to 0, but that's not how it's done in the code. The compute cost in the code will append 2 at last.
What does the 2 means?
https://github.com/alpa-projects/alpa/blob/2945fc4ea29e16ba7014e165e85624ed6d12b137/playground/auto_sharding_solver/hlo.py#L342
```
        for i in range(len(self.shape)):
            for j in range(len(cluster_env.device_mesh.shape)):
                if (cluster_env.device_mesh.shape[j] == 1 or
                    self.shape[i] < cluster_env.device_mesh.shape[j]):
                    continue

                name = f"S{i} @ {j}"
                output_spec = ShardingSpec.tile(self.shape, [i], [j], cluster_env)
                self.strategies.append(InstructionStrategy(name, output_spec))
                self.compute_costs.append(0)
                self.communication_costs.append(0)
                self.memory_costs.append(compute_bytes(self.shape) / output_spec.num_tile_devices())

        self.strategies.append(InstructionStrategy("R", ShardingSpec.replicated(cluster_env)))
        self.compute_costs.append(2)
        self.communication_costs.append(0)
```

**Comment by merrymercy** [comment]
1. This constraint is for donate_argnums (help: https://github.com/google/jax/blob/cf87e3a4a360c7a4b30b941df2ec290fb54ec201/jax/_src/api.py#L283). For donated arguments (or alias), we use this constraint to make the donation pair to have the same sharding spec, so they can share the same buffers
2. `alpa/playground/auto_sharding_solver` is a python prototype and it is not used. The real code is here https://github.com/alpa-projects/tensorflow-alpa/blob/a61c448887d4d3962189342a3f398497aab53abb/tensorflow/compiler/xla/service/spmd/auto_sharding.cc#L563-L564. We add a small penalty to fully replicated strategies to encourage more partitions, because fully replicated strategies consume more memory.

**Comment by kevinsouthxu** [comment]
> 1. For donated arguments (or alias), we use this constraint to make the tensors in a donation pair have the same sharding spec, so they can share the same buffers

I wonder what the donated arguments (or alias) is used for. Is it associated with the edges in the computation graph?

**Comment by kevinsouthxu** [comment]
> 1. This constraint is for donate_argnums (help: https://github.com/google/jax/blob/cf87e3a4a360c7a4b30b941df2ec290fb54ec201/jax/_src/api.py#L283). For donated arguments (or alias), we use this constraint to make the tensors in a donation pair have the same sharding spec, so they can share the same buffers
> 2. `alpa/playground/auto_sharding_solver` is a python prototype and it is not used. The real code is here https://github.com/alpa-projects/tensorflow-alpa/blob/a61c448887d4d3962189342a3f398497aab53abb/tensorflow/compiler/xla/service/spmd/auto_sharding.cc#L563-L564. We add a small penalty to fully replicated strategies to encourage more partitions, because fully replicated strategies consume more memory.

Thank you for your replying. I understand these two points.
