### ISSUE TITLE
[RUNTIME] NCCL broadcast based cross mesh resharding

### ISSUE THREAD

**Issue by TarzanZhao** [alpa-projects/alpa#416]
**Background**

To send a distributed tensor from one mesh to another, we need to perform cross mesh resharding. One cross mesh resharding problem could be decomposed many "N-to-M data send task". Basically, one tensor could be decomposed into many tensor slices, each tensor slice originally has copy in some devices in mesh A, we want to send the tensor slice to some other devices in mesh B. Mesh A and Mesh B have no common devices. By "N-to-M data send task", I mean one data resides in N source devices and sends to M target devices. 

Current implementation is based on NCCL send, recv and allgather operators. Basically, using send/recv to make each target device get a part of the data, then do local allgather to make each target device get the whole data. Sender could be chosen by balancing load. This solution perform optimally under most cases, but does not solve all. 

**NCCL broadcast based cross mesh resharding**

Consider if we only use one device as the data sender, i.e. N=1, then the "1-to-M data send task" is exactly NCCL broadcast is doing. I check the NCCL broadcast implementation, it is also ring based pipeline algorithm as shown in the figure below, similar to allreduce implementation. That implementation allows total execution time to be much shorter. You could refer [NCCL-operator-rationale.pdf](https://github.com/Avkash/mldl/blob/master/pages/docs/books/NCCL-Woolley.pdf). 

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/45677459/166100314-fd1588b7-14ce-45b7-be90-8fe445011f22.png">

When N is not 1, choosing arbitrary source device by load balancing to force N to be 1, could already achieve minimal cross host communication which is the bottleneck of speed. We could also create more broadcast tasks starting from different source devices and to different sets of adjacent target devices, so as to take advantage of concurrent execution. 

Theoretically, broadcast based implementation is optimal under all cases in terms of cross-host communication overhead. And ring-based implementation of NCCL broadcast with good load balancing could achieve even better/even optimal overall execution time. 

**Experiment results**

For single unit test by `tests/test_cross_mesh_resharding.py`, we could design resharding task on which broadcast based implementation is more than 4 times faster than send/recv+local allgather implementation as in the following task. Actually, we can design task on which broadcast based resharding is even much faster than send/recv+local allgather implementation, because we know current broadcast based resharding's shortcoming. 

<img width="527" alt="image" src="https://user-images.githubusercontent.com/45677459/166101854-9ca70105-8e88-4996-b543-973f068a5b6f.png">

For the following case, send/recv+local allgather resharding does not even support, but broadcast based implementation could run successfully and be very fast as expected. (Current send/recv+local allgather does not support two shard axis, in this example).

<img width="617" alt="image" src="https://user-images.githubusercontent.com/45677459/166102137-07e6fbd8-bb4e-48b6-8852-f74b491427ff.png">

In these normal cases which send/recv+local allgather resharding already achieve minimal cross-host communication overhead, broadcast based implementation achieves the same speed. 

For end-to-end training by `benchmark/alpa/benchmark_3d.py --suite `. I trained gpt and wresnet, broadcast based resharding achieved the same speed as send/recv+local allgather resharding. Because there is no special reshardingtask involved in these training. 

And the broadcast based resharding could solve/bypass this issue as expected: https://github.com/alpa-projects/alpa/issues/350 . Broadcast based resharding is faster because it does not need extra memcpy.  

**Future works**
1. I currently create nccl collective communicator on the fly, later I could create collective communicator before the whole training process. nccl collective communicator creation is slow. 
2. Currently, I only use one device as sender. Later I could further improve it by allow multiple broadcast for one "N-to-M data send task". This might further improve cross mesh resharding speed as mentioned above.

**Comment by merrymercy** [comment]
I like this idea. The formulation is cleaner. The performance is better. Broadcast also has several other advantages over send/recv. For example, I guess broadcast is more robust (less deadlock) and better optimized in nccl. Broadcast can also be better optimized with ring/tree-based algorithms. We should replace our current implementation with your proposal as soon as possible.

I do have several comments:
1. The broadcast-based formulation sounds simpler than senc/recv-based formulation. Is the implementation also simpler? How much can it simplify the implementation  (e.g., in terms of lines of code)?
2. You don't do load balance currently. Do you have an estimation of how the load balance affects the performance?
3. Creating the communicator before the training is preferred, we want to implement this before merging your code.

As your experimental results show, I think most of the development is done. You can clean up the code and submit pull requests for review.

**Comment by TarzanZhao** [comment]
> I like this idea. The formulation is cleaner. The performance is better. Broadcast also has several other advantages over send/recv. For example, I guess broadcast is more robust (less deadlock) and better optimized in nccl. Broadcast can also be better optimized with ring/tree-based algorithms. We should replace our current implementation with your proposal as soon as possible.
> 
> I do have several comments:
> 
> 1. The broadcast-based formulation sounds simpler than senc/recv-based formulation. Is the implementation also simpler? How much can it simplify the implementation  (e.g., in terms of lines of code)?
> 2. You don't do load balance currently. Do you have an estimation of how the load balance affects the performance?
> 3. Creating the communicator before the training is preferred, we want to implement this before merging your code.
> 
> As your experimental results show, I think most of the development is done. You can clean up the code and submit pull requests for review.

1. My Implementation is simpler than send/recv+based one. But it does not reduces too much lines of code, only 200 or so for now. Even though it only involves step, this one step is a little bit more complex. 
2. It depends. But I think we indeed need multiple broadcasts for one "N-to-M data send task" if device mesh involves too many host. At least, this improvement should not give worse result with good implementation of load balancing(May take underlining topology into account).
3. OK

**Comment by zhuohan123** [comment]
What's your plan when there are more than one senders? If I understand correctly, the current strategy is randomly group M receivers into N groups, and each group received from one specific sender? Do you have plan on how to improve this? Specifically, current strategy will be actually slower if multiple senders are on the same node and they share the same NIC.

**Comment by TarzanZhao** [comment]
> What's your plan when there are more than one senders? If I understand correctly, the current strategy is randomly group M receivers into N groups, and each group received from one specific sender? Do you have plan on how to improve this? Specifically, current strategy seems to be slower if multiple senders are on the same node and they share the same NIC.

Currently, I only choose one sender by loads for the "N-to-M data send task" defined above. My following work is load-balancing on different levels, then I will group M receivers into N groups based on locality and loads of sender and receiver. What you are talking about is exactly load-balancing, I will propose one solution in more details later.

**Comment by merrymercy** [comment]
closed by #425
