### ISSUE TITLE
[RUNTIME] Deprecate cupy.cuda.nccl and export nccl APIs from xla

### ISSUE THREAD

**Issue by merrymercy** [alpa-projects/alpa#432]
# Background
Currently, Alpa uses cupy as the python API binding for nccl. This causes two problems
- We need to do conversion between cupy tensors and xla tensors. Although we can achieve zero-copy through dlpack, this part of code is error-prune and hacky.
- There can be conflicts between the nccl used by cupy and the nccl used by XLA. `cupy.nccl` and [`xla/nccl_utils`](https://github.com/alpa-projects/tensorflow-alpa/blob/master/tensorflow/compiler/xla/service/gpu/nccl_utils.cc) can initialize and call two different versions of nccl if we don't link or compile them correctly. This leads to unknown hanging issues.

To fix these problems, we can deprecate `cupy.nccl` and export NCCL apis from XLA. This makes sure we only use one version of nccl and avoids tensor conversion.

# TODO
  - [x] Export NCCL APIs from XLA
      - See also [cupy/nccl.pyx](https://github.com/cupy/cupy/blob/master/cupy_backends/cuda/libs/nccl.pyx), [xla/nccl_utils.cc](https://github.com/alpa-projects/tensorflow-alpa/blob/master/tensorflow/compiler/xla/service/gpu/nccl_utils.cc)
      - Implement c++ functions in [xla/nccl_utils.cc](https://github.com/alpa-projects/tensorflow-alpa/blob/master/tensorflow/compiler/xla/service/gpu/nccl_utils.cc)
      - Implement bind in [xla.cc](https://github.com/alpa-projects/tensorflow-alpa/blob/78388ccb16ad1d23d989cec0958feefebcf19177/tensorflow/compiler/xla/python/xla.cc#L550)
      - Call c++ functions by [xla_extension](https://github.com/alpa-projects/alpa/blob/0d212eb4cb45a375c0f25bd305ba537f4ad753c4/alpa/shard_parallel/auto_sharding.py#L31)
      - Add nccl_utils to [BUILD](https://github.com/alpa-projects/tensorflow-alpa/blob/78388ccb16ad1d23d989cec0958feefebcf19177/tensorflow/compiler/xla/python/BUILD#L684)
  - [x] Replace all usage of `cupy.nccl` in alpa with the NCCL APIs exported from XLA
       - xla uses stream_executor instead of the most original CUDA stream APIs
       - get rid of cupy, dlpack tensor types, and use XLA DeviceArray directly. Make sure the arrays are well synced since they are on GPUs
       - XLA DeviceArray is not indexable, so it might require some special handling, e.g., converted to JAX. All conversion needs to be zero-copy
       - How to handle the FREE instruction

**Comment by zhuohan123** [comment]
@scv119 Are you interested in this issue? It's related to how alpa runtime deals with GPUs and should be helpful for you to explore how alpa runtime works.

**Comment by zhisbug** [comment]
@TarzanZhao

**Comment by TarzanZhao** [comment]
OK
