### ISSUE TITLE
[Refactor] Rename DecentralizedDistributedRuntime to PipelineDriverExecutable

### ISSUE THREAD

**Issue by merrymercy** [alpa-projects/alpa#443]
After we support multiple computational graphs, `DecentralizedDistributedRuntime` is not a runtime anymore. It is the driver part of an executable. The actual runtime should be `DistributedPhysicalDeviceMeshGroup`.

Similar to what we did for shard_parallel (see `alpa/mesh_executable.py`). Each executable has a driver part and a worker part. Currently, the name of the work part is correct. 
https://github.com/alpa-projects/alpa/blob/30a66d543d2b68225ea233313739260e41c46cef/alpa/pipeline_parallel/decentralized_distributed_runtime.py#L1102

But for the driver part, we should rename `DecentralizedDistributedRuntime`, `BaseDistributedRuntime`, etc to `XXXPipelineDriverExecutable`.

**Comment by merrymercy** [comment]
cc @zhuohan123 @zhisbug @ZYHowell

**Comment by ZYHowell** [comment]
I like this idea. But I think there are two things beyond simply renaming the class:
1. Design the interface of `MeshDriverExecutable` and `MeshWorkerExecutable`. By this interface, methods like `launch_on_driver`, `execute_on_worker`, `hlo_text`, `memory_allocation` can be unified between `shard_parallel` and `pipeshard_parallel`.
2. Move the initialization of cross mesh communicator out from `XXXDistributedRuntime` (now `PipelineMeshDriverExecutable`). Communicators are physical resources rather than executables, so it's better to manage them together with `DeviceMeshGroup`.

**Comment by zhuohan123** [comment]
Nit: Maybe call it `PipeshardDriverExecutable` to respect that it uses both pipeline and shard parallelism.

**Comment by zhuohan123** [comment]
> 2. Move the initialization of cross mesh communicator out from `XXXDistributedRuntime` (now `PipelineMeshDriverExecutable`). Communicators are physical resources rather than executables, so it's better to manage them together with `DeviceMeshGroup`.

The physical part is already in `DistributedPhysicalDeviceMeshGroup` now: https://github.com/alpa-projects/alpa/blob/64f620381c47678a03e6fc3e3fd9dbb818cfa7e4/alpa/pipeline_parallel/device_mesh_group.py#L28

**Comment by ZYHowell** [comment]
> 
> The physical part is already in `DistributedPhysicalDeviceMeshGroup` now:
> 
> https://github.com/alpa-projects/alpa/blob/64f620381c47678a03e6fc3e3fd9dbb818cfa7e4/alpa/pipeline_parallel/device_mesh_group.py#L28

So we should move code in this line to the function you mentioned
https://github.com/alpa-projects/alpa/blob/64f620381c47678a03e6fc3e3fd9dbb818cfa7e4/alpa/pipeline_parallel/base_runtime.py#L122

**Comment by zhuohan123** [comment]
> Then we should move code in this line to the function you mentioned
> 
> https://github.com/alpa-projects/alpa/blob/64f620381c47678a03e6fc3e3fd9dbb818cfa7e4/alpa/pipeline_parallel/base_runtime.py#L122

We leave this code here because different executables might require nccl groups between different meshes. If we build nccl groups in mesh group class, we need to start all n^2 groups at the beginning, which is wasteful in general.

**Comment by merrymercy** [comment]
I will work on starting from this tonight. Are there any conflicts?

**Comment by zhuohan123** [comment]
Done in #451.
