### ISSUE TITLE
[Doc] Distributed Save Load documentation

### ISSUE THREAD

**Issue by zhisbug** [alpa-projects/alpa#455]
@PKUFlyingPig It'd be good to document the usage of save and load interfaces for the PR #437 

Consider adding an page "API" [here](https://github.com/alpa-projects/alpa/blob/main/docs/index.rst)

**Comment by PKUFlyingPig** [comment]
Sure, but how to build the documentation offline to check my progress?

**Comment by zhisbug** [comment]
https://github.com/alpa-projects/alpa/blob/main/docs/README.md

**Comment by merrymercy** [comment]
I think the API is not stable yet. It will be refactored by https://github.com/alpa-projects/alpa/issues/439.
We can put off the documentation

**Comment by PKUFlyingPig** [comment]
OK. Also, I think the "parallel options API" refactored by #451 should be mentioned in the "API" page in documentation.
