### ISSUE TITLE
How alpa lower control flow jaxpr into XLA HLO?

### ISSUE THREAD

**Issue by adamantboy** [alpa-projects/alpa#490]
for example,cond:
```
>>> from jax import lax
>>>
>>> def func7(arg):
...   return lax.cond(arg >= 0.,
...                   lambda xtrue: xtrue + 3.,
...                   lambda xfalse: xfalse - 3.,
...                   arg)
...
>>> print(make_jaxpr(func7)(5.))
{ lambda ; a:f32[]. let
    b:bool[] = ge a 0.0
    c:i32[] = convert_element_type[new_dtype=int32 weak_type=False] b
    d:f32[] = cond[
      branches=(
        { lambda ; e:f32[]. let f:f32[] = sub e 3.0 in (f,) }
        { lambda ; g:f32[]. let h:f32[] = add g 3.0 in (h,) }
      )
      linear=(False,)
    ] c a
  in (d,) }
```
In this situation, how alpa deal with cond eqns if we want to lower it into XLA HLO? @zhisbug

**Comment by merrymercy** [comment]
This is not supported yet, we are working on supporting it. see also https://github.com/alpa-projects/alpa/issues/400

**Comment by adamantboy** [comment]
> This is not supported yet, we are working on supporting it. see also #400

There is one thing important, the way alpa use to transform jaxpr into hlo is called “initial-style higher-order primitive”, this approach can’t support data-dependent Python control flow. See [jax autodidax](https://jax.readthedocs.io/en/latest/autodidax.html), part 3.

**Comment by merrymercy** [comment]
`alpa.parallelize` is similar to `jax.jit`. Both of them do not aim to support data-dependent python control flow currently. You can still write control flow with `lax.while_loop` and `lax.cond`.

Just curious, what is your usage? When do you need data-dependent control flow?

**Comment by adamantboy** [comment]
> `alpa.parallelize` is similar to `jax.jit`. Both of them do not aim to support data-dependent python control flow currently. You can still write control flow with `lax.while_loop` and `lax.cond`.
> 
> Just curious, what is your usage? When do you need data-dependent python control flow?

Some detection models have data-dependent control flow, i just worry that if alpa can support it. By the way, do you know the global tensor mechanism of alpa, i'm confused, how alpa associate global tensor with mesh worker tensor in PipeshardDriverExecutable, there is no document about it!

**Comment by zhisbug** [comment]
@adamantboy Yeah currently documentation on pre-sharding input tensors are missing.

You can start by reading the code here: https://github.com/alpa-projects/alpa/blob/main/alpa/device_mesh.py#L943
and dive into the sharding implementations like [this](https://github.com/alpa-projects/alpa/blob/0c29f5909b015da5112dec1af95dbcfd8a4fb722/alpa/mesh_executable.py#L360)

**Comment by merrymercy** [comment]
The driver process use [DistributedArray](https://github.com/alpa-projects/alpa/blob/9f41aa3cc95fcb99babddf97360d50ab657172a7/alpa/device_mesh.py#L1382) to manage a distributed tensor.
The driver stores uuids of the remote buffers as pointers.

**Comment by merrymercy** [comment]
I think the original question is answered. We can close this issue and move control flow related discussion to #400, move other questions to new issues.
