### ISSUE TITLE
[QUESTION] where does Alpa generate intra-operator strategies in Alpa's code

### ISSUE THREAD

**Issue by kevinsouthxu** [alpa-projects/alpa#494]

**Comment by ZYHowell** [comment]
The entrance is [this function](https://github.com/alpa-projects/alpa/blob/3995d72359f78edaf54de7bc8fe9bdd2c2d8d680/alpa/shard_parallel/auto_sharding.py#L159-L364)
Using ILP to generate the strategy is at [here](https://github.com/alpa-projects/tensorflow-alpa/blob/03f4e261b81a674c0a87044062042f1647d2ca07/tensorflow/compiler/xla/service/spmd/auto_sharding.cc#L1727-L1763).
