### ISSUE TITLE
Adding the `pjit` in the comparison

### ISSUE THREAD

**Issue by JiahaoYao** [alpa-projects/alpa#505]
Some people are more familiar with using model parallel via [`pjit`](https://github.com/google/jax/blob/main/jax/experimental/pjit.py). What about adding one more rows [here](https://github.com/alpa-projects/alpa/blob/main/docs/gallery/tutorials/alpa_vs_pmap.py#L46-L52)?

**Comment by merrymercy** [comment]
Pjit will be exactly the same as xmap in this table.  I can add it later
