### ISSUE TITLE
Check aval init shape and runtime batch shape

### ISSUE THREAD

**Issue by zhisbug** [alpa-projects/alpa#510]
### Background
Our example code and test cases now use the interface `train_step.get_executable()` very extensively. 
Many users will mimic our usage of this function, though they are not expected to use this interface.

### Please describe the bug
One issue with using this interface:
- Say the user triggers the compilation via `get_executable({"input1": ShapedArray((x1, y1)), ...})` with `num_micro_batch = n`
- At runtime, however, the users pass an actual array `jnp.ones((x2, y2))`

Alpa will have the following behaviors:
- if `y2 != y1`, since it is not the batch dimension, an error like [the one in this issue](https://github.com/alpa-projects/alpa/issues/506) will be thrown, which is OK, though not quite informative.
- if `x2 != n * x1`, e.g., `x1 = 1`, `n =1`, and `x2=512`, the program will still run w**ithout an error** because we do not check the consistency between the shape of the passed input at runtime and the shape declared by `get_executable()`.
Because of [this line](https://github.com/alpa-projects/alpa/blob/dcdfd162fa5dee55ad8fc4b5f3b682b5528072b0/alpa/device_mesh.py#L2173), the program will silently run by slice the first row of the input with shape `(512, y1)` and ignore the rest.

### Please describe the expected behavior
We should:
- either check the shapes at init and at runtime to make sure they match and raise an informative error if they do not.
- discourage the usage of `get_exectuable()`

**Comment by merrymercy** [comment]
Did you use https://github.com/alpa-projects/alpa/blob/dcdfd162fa5dee55ad8fc4b5f3b682b5528072b0/alpa/pipeline_parallel/pipeshard_executable.py#L234-L235 ?
This is indented because we want to reduce runtime overhead.

```
executable = train_step.get_executable

# has shape check
train_step(...) 
# no shape check
executable(...)
```

In our test cases and benchmark scripts, we usually `train_step(...)`. In opt inference demo, I use `executable(...)` for less runtime overhead

**Comment by zhisbug** [comment]
OK, that means it is safe in benchmarking code
