### ISSUE TITLE
Device indices mismatch and assert failure

### ISSUE THREAD

**Issue by insujang** [alpa-projects/alpa#515]
**Please describe the bug**

Trying to run `benchmark/alpa/gen_prof_database.py` with 2 nodes, 4 GPUs each.
But assertion fails in device_mesh.py as follows:

```
Mesh shape: (2, 4)
Traceback (most recent call last):
  File "gen_prof_database.py", line 54, in <module>
    prof_database = cluster.profile_all(
  File "/data/insujang/alpa/alpa/device_mesh.py", line 2078, in profile_all
    return mesh_profiling.profile_all(self, *args, **kwargs)
  File "/data/insujang/alpa/alpa/mesh_profiling.py", line 754, in profile_all
    tmp_mesh = virtual_mesh.slice_2d(
  File "/data/insujang/alpa/alpa/device_mesh.py", line 1754, in slice_2d
    assert x in self.devices[i]
AssertionError
```

```python
    def slice_2d(self, host_indices, device_indices):
        host_ids = [self.host_ids[x] for x in host_indices]
        host_info = [self.host_info[x] for x in host_indices]

        # Check the validity of device_indices
        for i in range(len(device_indices)):
            for x in device_indices[i]:
                assert x in self.devices[i] (line 1754 in master)
```
where `device_incides` and `self.devices` are
```
device_indices
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
self.devices
[[0, 1, 2, 3], [0, 1, 2, 3]]
```

Is that a bug? How do I run full profiling with multiple nodes?

**Please describe the expected behavior**

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): RHEL 8.5, Docker container (PyTorch with CUDA 11.3, CUDNN 8)
- Python version: 3.8.12
- CUDA version: 11.3
- NCCL version: 
- cupy version: 113
- GPU model and memory: NVIDIA A40 40GB
- Alpa version: master
- TensorFlow version: X
- JAX version:

**To Reproduce**
1. Use 2 nodes with 4 GPUs. Followed [install guideline](https://alpa-projects.github.io/install.html) to install Alpa.
2. Clone Alpa repository and run: `python3 alpa/benchmark/alpa/gen_prof_database.py --max-comm-size-intra-node 32 --max-comm-size-inter-node 29`
3. See error

**Screenshots**

**Code snippet to reproduce the problem**

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by zhisbug** [comment]
Hello @insujang , thanks for your interest!

I think this might be a bug, one of the argument passed to `slice_2d` is wrong:

https://github.com/alpa-projects/alpa/blob/12e65970cb240797b4a3a8e34517bc6705603ab1/alpa/mesh_profiling.py#L754-L758

Could you try:
```python
        tmp_mesh = virtual_mesh.slice_2d(
            list(range(num_hosts)),
            np.tile(np.arange(num_devices_per_host), (num_hosts, 1)))
```

**Comment by zhuohan123** [comment]
Yes. This should be a bug. Let me submit a PR to fix this.

**Comment by insujang** [comment]
Thanks @zhisbug @zhuohan123 ! It looks the modification works. Now I am facing another error regarding a Ray exception from MeshHostWorker when getting available memory, but let me post it later after trying more. Thanks!

**Comment by merrymercy** [comment]
https://github.com/alpa-projects/alpa/pull/518
