### ISSUE TITLE
[utils] allocate gpu resources 

### ISSUE THREAD

**Issue by JiahaoYao** [alpa-projects/alpa#520]
currently, alpa uses `update_jax_platform` to gives out the gpu resources to `alpa`.

```python
def update_jax_platform(platform):
    """Update the jax backend platform."""
    jax.config.update("jax_platform_name", platform)
    xb.get_backend.cache_clear()
```

I wonder whether it is possible to have GPU affinity. like partial hide / release gpu resources? One approach i can think about is to use `CUDA_VISIBLE_DEVICES`? but it seems if there are two separate `alpa` processs running on the same node, it can cause conflicts.

**Comment by zhisbug** [comment]
misclicked `close`

**Comment by JiahaoYao** [comment]
close this because long time inactivity
