### ISSUE TITLE
The alpa server is down

### ISSUE THREAD

**Issue by ImproveTheNewsFoundation** [alpa-projects/alpa#553]
Hello, the alpa installation page installs alpa modified Jax-lib from http://169.229.48.123:8080/simple/ which is broken. Please fix!

**Comment by zhisbug** [comment]
@ImproveTheNewsFoundation Just restarted -- please let me know if you still see the issue!

**Comment by wgimperial** [comment]
Modifyed Jax-lib from  http://169.229.48.123:8080/simple/ failed. 
There are other ways to download jaxlib==0.3.5 ?

**Comment by zhisbug** [comment]
@chaosGuppy @wgimperial restarted -- try agin. We'll try to migrate to a more stable server

**Comment by wgimperial** [comment]
is alpa server is down again?
