### ISSUE TITLE
[BUG] OPT benchmark forward-only mode cannot run with prompt length cannot divisible by power of 2

### ISSUE THREAD

**Issue by zhuohan123** [alpa-projects/alpa#561]
Create this issue to track Cody's bug. To reproduce, run:

```
python3 benchmark_text_gen.py --model alpa/opt-2.7b --path ~/opt_weights --forward --decoder-length=6
```

**Comment by merrymercy** [comment]
https://github.com/alpa-projects/tensorflow-alpa/pull/122

**Comment by merrymercy** [comment]
@comaniac Solved by https://github.com/alpa-projects/alpa/pull/574. Please update tensorflow-alpa submodule and compile jaxlib again
