### ISSUE TITLE
Distributed Generation Script - benchmark_text_gen.py - CUDA related error

### ISSUE THREAD

**Issue by BalajiAJ** [alpa-projects/alpa#570]
HI,

While running the ray and ```benchmark_text_gen.py``` script, I see an error related to CUDA (snapshot below). I have verified the CUDA, CUDNN versions and GPU info and everything looks fine. Any possible hints on this.

cuda:	11.3
cudnn:	8.2
gcc:  	11.3.0

![image](https://user-images.githubusercontent.com/19531638/176964350-b790ef8a-1319-4c20-a5d9-b48ec4854291.png)

**Comment by zhisbug** [comment]
1. What is the GPU you are using?
2. Can you run on smaller version of OPT?

**Comment by BalajiAJ** [comment]
> 1. What is the GPU you are using?
> 2. Can you run on smaller version of OPT?

1. Nvidia 16 GPUs of A 100 40 GB. 
2. Tried running 2.7bmodel same error.

**Comment by zhisbug** [comment]
@BalajiAJ It seems your cuda driver isn't launching. What is your driver version? And can you run `python tests/test_install.py` successfully?

**Comment by BalajiAJ** [comment]
> @BalajiAJ It seems your cuda driver isn't launching. What is your driver version? And can you run `python tests/test_install.py` successfully?

Hi @zhisbug I have configured a new VM with all the required GPU's and memory. Have verified the installed verions of cuda, cudnn, nccl etc. and everything looked fine. I have the below and got same error again. Please advise. Thanks!

```
!python3 test_install.py
```

Error:

![image](https://user-images.githubusercontent.com/19531638/177052967-eb6e6ce9-bbc8-4c20-9ee6-038364b92560.png)

**Comment by zhisbug** [comment]
@BalajiAJ 

1. Please `cd third_party/tensorflow-alpa` and `git log` and report the latest commit id
2. Could you run the files under `benchmark/cupy`

**Comment by zhuohan123** [comment]
@BalajiAJ Is your GPU driver version `>= 460.xx.xxx`? We met errors caused by too old GPU driver version. The driver version is independent with the CUDA/CUDNN version. You can get this info by running `nvidia-smi`.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/17310766/177056821-9465f33e-026e-4cb9-bfd5-9e508a170af8.png">

**Comment by BalajiAJ** [comment]
> @BalajiAJ
> 
> 1. Please `cd third_party/tensorflow-alpa` and `git log` and report the latest commit id
> 2. Could you run the files under `benchmark/cupy`

@zhisbug Here are my responses
1.  I have installed alpa through wheel file (pip install alpa) and installed version is shown as 0.1.3.
2. 

> @BalajiAJ Is your GPU driver version `>= 460.xx.xxx`? We met errors caused by too old GPU driver version. The driver version is independent with the CUDA/CUDNN version. You can get this info by running `nvidia-smi`. <img alt="image" width="663" src="https://user-images.githubusercontent.com/17310766/177056821-9465f33e-026e-4cb9-bfd5-9e508a170af8.png">

@zhisbug  This is my Nvidia driver version:

![image](https://user-images.githubusercontent.com/19531638/177073328-0306c042-5310-4b67-8c5f-f1aa858dc7fc.png)

**Comment by BalajiAJ** [comment]
> @BalajiAJ
> 
> 1. Please `cd third_party/tensorflow-alpa` and `git log` and report the latest commit id
> 2. Could you run the files under `benchmark/cupy`

Hi @zhisbug , here are my responses below. I have installed alpa from wheel file (pip install alpa) and installed version shows as 0.1.3.
1. git log details:
![image](https://user-images.githubusercontent.com/19531638/177074685-b5edbb91-97d9-4715-809e-86f42754f647.png)

2. On running files from benchmark/cupy, am getting the same cudaerrorlaunch failure error. Please advise.

**Comment by merrymercy** [comment]
Some tips in this issue https://github.com/alpa-projects/alpa/issues/496 may be helpful

**Comment by BalajiAJ** [comment]
> Some tips in this issue #496 may be helpful

@merrymercy Thank you so much. The suggestions is #496 helped me to launch the cuda and run the benchmark script successfully.

@zhisbug One quick suggestion needed. I am getting below error while running interactive hosted script, related to cython. 

I have installed alpa using whl file (``` pip install alpa ```). Please let me know if I have to run the cython related installation (``` pip install --editable . ```) from installed location of alpa (``` /opt/conda/lib/python3.7/site-packages/examples/opt_serving/ ```) or from cloned Github repo folder?
```
```Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "interactive_hosted.py", line 104, in batching_loop
    generations = generator.generate(**request_object)
  File "/opt/conda/lib/python3.7/site-packages/examples/opt_serving/generator.py", line 377, in generate
    dataset=self.build_dataset_for_inference(tokens, lengths),
  File "/opt/conda/lib/python3.7/site-packages/examples/opt_serving/generator.py", line 540, in build_dataset_for_inference
    break_mode="eos")
  File "/opt/conda/lib/python3.7/site-packages/examples/opt_serving/dataset/token_block_dataset.py", line 73, in __init__
    sizes, break_mode, document_sep_len, block_size)
  File "/opt/conda/lib/python3.7/site-packages/examples/opt_serving/dataset/token_block_dataset.py", line 115, in _build_slice_indices
    "Please build Cython components with: `pip install --editable .` "
ImportError: Please build Cython components with: `pip install --editable .` or `python setup.py build_ext --inplace
```

**Comment by BalajiAJ** [comment]
> > Some tips in this issue #496 may be helpful
> 
> @merrymercy Thank you so much. The suggestions is #496 helped me to launch the cuda and run the benchmark script successfully.
> 
> @zhisbug One quick suggestion needed. I am getting below error while running interactive hosted script, related to cython.
> 
> I have installed alpa using whl file (`pip install alpa`). Please let me know if I have to run the cython related installation (`pip install --editable .`) from installed location of alpa (`/opt/conda/lib/python3.7/site-packages/examples/opt_serving/`) or from cloned Github repo folder?
> 
> ```
> ```Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "/opt/conda/lib/python3.7/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "interactive_hosted.py", line 104, in batching_loop
>     generations = generator.generate(**request_object)
>   File "/opt/conda/lib/python3.7/site-packages/examples/opt_serving/generator.py", line 377, in generate
>     dataset=self.build_dataset_for_inference(tokens, lengths),
>   File "/opt/conda/lib/python3.7/site-packages/examples/opt_serving/generator.py", line 540, in build_dataset_for_inference
>     break_mode="eos")
>   File "/opt/conda/lib/python3.7/site-packages/examples/opt_serving/dataset/token_block_dataset.py", line 73, in __init__
>     sizes, break_mode, document_sep_len, block_size)
>   File "/opt/conda/lib/python3.7/site-packages/examples/opt_serving/dataset/token_block_dataset.py", line 115, in _build_slice_indices
>     "Please build Cython components with: `pip install --editable .` "
> ImportError: Please build Cython components with: `pip install --editable .` or `python setup.py build_ext --inplace
> ```

@zhisbug could you please guide on the above question, regarding cython components build for alpa. Thanks!!

**Comment by merrymercy** [comment]
Hi, we updated alpa to version v0.1.4. We also did some improvements to the organization of opt_serving. 

Please pip uninstall alpa and pip install alpa again. Then you can follow these steps (mainly step 4) to build cython components https://alpa-projects.github.io/tutorials/opt_serving.html#requirements

**Comment by zhisbug** [comment]
@BalajiAJ This might be a simple namespace importing conflict. we (unsafely) use the `examples` as a Python package name. There are a lot of `from examples.opt_serving.xxx import yyy`. I guess your Python has some trouble resolving these import. 

You can refer to [this thread ](https://github.com/alpa-projects/alpa/issues/566#issuecomment-1172817226) and try some similar fix?

In the recent release (v0.1.4), @merrymercy fixed this issue (see his reply above).

**Comment by zhisbug** [comment]
@BalajiAJ See this PR for more information: https://github.com/alpa-projects/alpa/pull/589#event-6929171772

**Comment by BalajiAJ** [comment]
> Hi, we updated alpa to version v0.1.4. We also did some improvements to the organization of opt_serving.
> 
> Please pip uninstall alpa and pip install alpa again. Then you can follow these steps (mainly step 4) to build cython components https://alpa-projects.github.io/tutorials/opt_serving.html#requirements

@merrymercy Thank you so much for your quick help. the issues are resolved now and am able to run the OPT-175B inferencing.

**Comment by BalajiAJ** [comment]
> @BalajiAJ This might be a simple namespace importing conflict. we (unsafely) use the `examples` as a Python package name. There are a lot of `from examples.opt_serving.xxx import yyy`. I guess your Python has some trouble resolving these import.
> 
> You can refer to [this thread ](https://github.com/alpa-projects/alpa/issues/566#issuecomment-1172817226) and try some similar fix?
> 
> In the recent release (v0.1.4), @merrymercy fixed this issue (see his reply above).

@zhisbug Thanks a lot for all the quick guidance and issue resolution steps. I am able to run the model without any errors. Thanks again. Appreciate your timely support!
