### ISSUE TITLE
pipeshard_parallelism.py not working

### ISSUE THREAD

**Issue by wonjeon** [alpa-projects/alpa#572]
**Please describe the bug**

While following up the instruction described at https://alpa-projects.github.io/tutorials/pipeshard_parallelism.html, an error occurred.

```
$ python3 pipeshard_parallelism.py
...
  File "/home/wjeon/.local/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1774, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/wjeon/.local/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "pipeshard_parallelism.py", line 151, in manual_pipeline_train_step
    @alpa.manual_layer_construction
jax._src.traceback_util.UnfilteredStackTrace: AttributeError: module 'alpa' has no attribute 'manual_layer_construction'

```
**Please describe the expected behavior**

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Linux Ubuntu 20.04
- Python version: 3.8.10
- CUDA version: 11.1
- NCCL version: 2.12.12
- cupy version: 10.5.0
- GPU model and memory:
- Alpa version: 0.0.0 (build from source)
- TensorFlow version:
- JAX version: 0.3.5 (build from source)

**To Reproduce**
1. Download pipeshard_parallelism.py from https://alpa-projects.github.io/tutorials/pipeshard_parallelism.html.
2. Run 'python3 pipeshard_parallelism.py'.
3.

**Screenshots**

**Code snippet to reproduce the problem**

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by merrymercy** [comment]
Hi, we just updated the API. Please use the new version here https://github.com/alpa-projects/alpa/blob/main/docs/gallery/tutorials/pipeshard_parallelism.py.
The website is a little bit stale and will be updated in one hour.

**Comment by merrymercy** [comment]
Thanks for reporting. The website is updated
