### ISSUE TITLE
For help running opt-demo with alpa

### ISSUE THREAD

**Issue by wgimperial** [alpa-projects/alpa#595]
**Please describe the bug**
Run opt-demo whth alpa,follow https://alpa-projects.github.io/tutorials/opt_serving.html.
The demo cannot finished even minutes，Manual termination alway see the same info：

  File "demo.py", line 23, in <module>
    output = model.generate(input_ids=input_ids, max_length=256, do_sample=True)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/transformers/generation_utils.py", line 1320, in generate
    return self.sample(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/transformers/generation_utils.py", line 1938, in sample
    outputs = self(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/examples/opt_serving/model/wrapper.py", line 96, in __call__
    ret = self.inference_func(input_ids[:, i:i + 1],
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/examples/opt_serving/model/wrapper.py", line 278, in inference_func
    output = executable(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/pipeshard_executable.py", line 221, in __call__
    out = self.launch_on_driver(*args_flat)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/pipeshard_executable.py", line 202, in launch_on_driver
    self._check_alive()
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/pipeshard_executable.py", line 344, in _check_alive
    ray.get(rets)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/ray/worker.py", line 1825, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/ray/worker.py", line 364, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 1200, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 169, in ray._raylet.check_status

while the nvidia-smi command show：
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:88:00.0 Off |                    0 |
| N/A   39C    P0    27W /  70W |  13701MiB / 15109MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   42C    P0    27W /  70W |  13699MiB / 15109MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:B3:00.0 Off |                    0 |
| N/A   41C    P0    28W /  70W |  13727MiB / 15109MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:B4:00.0 Off |                    0 |
| N/A   39C    P0    27W /  70W |  14233MiB / 15109MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1687      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      7322      C   python                             99MiB |
|    0   N/A  N/A      8068      C   ...stWorker.run_executable()    13595MiB |
|    1   N/A  N/A      1687      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      7322      C   python                             99MiB |
|    1   N/A  N/A      8068      C   ...stWorker.run_executable()    13593MiB |
|    2   N/A  N/A      1687      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A      7322      C   python                             99MiB |
|    2   N/A  N/A      8069      C   ...stWorker.run_executable()    13621MiB |
|    3   N/A  N/A      1687      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A      7322      C   python                            605MiB |
|    3   N/A  N/A      8069      C   ...stWorker.run_executable()    13621MiB |
+-----------------------------------------------------------------------------+

For help，any ideas for investigation?

**Comment by merrymercy** [comment]
If you installed the latest version v0.1.4 of alpa (https://pypi.org/project/alpa/), could you run
```
ray start --head
python3 -m alpa.test_install
```

**Comment by wgimperial** [comment]
> If you installed the latest version v0.1.4 of alpa (https://pypi.org/project/alpa/), could you pass the following test?
> 
> ```
> ray start --head
> python3 -m alpa.test_install
> ```
> 
> I saw you successfully ran the demo in this post ([#579 (comment)](https://github.com/alpa-projects/alpa/issues/579#issuecomment-1175031728)). What is the difference between this failed run and your successful run?

Yes，I installed the latest version v0.1.4 of alpa.
”python3 -m alpa.test_install” also cannot finished .

I have success run on another server，This two servers has the same system（ubuntu20.04）、nvidia driver（470.129.06），and the same docker image（with the cuda&cudnn）。
The only difference is that one is online and the other is offline when the operating system is installed。Could this have an impact?

**Comment by zhisbug** [comment]
@wgimperial what's the solution you ended up with?

**Comment by wgimperial** [comment]
We tested and found that it may be a problem with the machine，so we will first check the impact of the machine。
