### ISSUE TITLE
Question on Fine-tuning OPT large models

### ISSUE THREAD

**Issue by BalajiAJ** [alpa-projects/alpa#599]
Hello, 

Does alpa provide the capabilities of fine-tuning OPT based models - 13B/30B models, for task specific datasets. If Yes, what would be the total GPU RAM required for the same. Any suggestions/reference guide available? Thanks!

**Comment by wgimperial** [comment]
you have 60B  model adapted  to alpa  ?

**Comment by BalajiAJ** [comment]
> you have 60B model adapted to alpa ?

@wgimperial Sorry, by mistake added, removed it from the original question now. Thanks!

**Comment by zhuohan123** [comment]
@merrymercy is working on this. I think it should be ready in 1~2 weeks. Stay tuned! At the same time you can take a look at [this page](https://alpa-projects.github.io/tutorials/pipeshard_parallelism.html) and get familiar with Alpa API.

**Comment by merrymercy** [comment]
#639

**Comment by merrymercy** [comment]
@BalajiAJ An example is added #639
