### ISSUE TITLE
merge 60B opt model

### ISSUE THREAD

**Issue by wgimperial** [alpa-projects/alpa#600]
use step_2_consolidate_992_shards_to_singleton.py to merge 66B shard fail ,report
Traceback (most recent call last):
  File "step_2_consolidate_992_shards_to_singleton.py", line 485, in <module>
    consolidate_fsdp_shards(args.read_prefix,
  File "step_2_consolidate_992_shards_to_singleton.py", line 153, in consolidate_fsdp_shards
    metadata.append(ckpt["shard_metadata"])
KeyError: 'shard_metadata'

**Comment by zhisbug** [comment]
@wgimperial How did you find the metadata?

**Comment by apoorvumang** [comment]
@wgimperial how did you solve this? Any help is appreciated 😃

**Comment by zhisbug** [comment]
@apoorvumang what's the problem you met when converting the 60B model following our procedures?

**Comment by yingapple** [comment]
> @apoorvumang what's the problem you met when converting the 60B model following our procedures?

I also meet this problem. It seems alpa's code donot fit for new opt model weight.
