### ISSUE TITLE
Question to the benchmark result

### ISSUE THREAD

**Issue by wgimperial** [alpa-projects/alpa#609]
**Please describe the bug**
Run benchmark  with command：
"python benchmark_text_gen.py --model alpa/opt-30b --path /opt-30b --debug"

1、In the case of 3 nodes，each with 16G×4 T4 GPU，total cost 594s，
2、In the case of 2 nodes，each with 16G×4 T4 GPU，total cost 563s，

Why do more GPUs run less efficiently?

We noticed uneven GPU utilization when running benchmark，Is this a possible cause of the problem?

Thu Jul 14 17:07:15 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:18:00.0 Off |                    0 |
| N/A   50C    P0    85W /  70W |  13401MiB / 15109MiB |     90%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   49C    P0    37W /  70W |  13401MiB / 15109MiB |     89%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:86:00.0 Off |                    0 |
| N/A   50C    P0    38W /  70W |  13401MiB / 15109MiB |     89%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   52C    P0    35W /  70W |  13401MiB / 15109MiB |     89%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

Thu Jul 14 17:07:43 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:18:00.0 Off |                    0 |
| N/A   50C    P0    34W /  70W |  13411MiB / 15109MiB |     70%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   50C    P0    33W /  70W |  13411MiB / 15109MiB |     61%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:86:00.0 Off |                  Off |
| N/A   47C    P0    33W /  70W |  14307MiB / 16127MiB |     63%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   48C    P0    38W /  70W |  13917MiB / 15109MiB |     70%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

Thu Jul 14 17:07:33 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:18:00.0 Off |                    0 |
| N/A   41C    P0    27W /  70W |  13400MiB / 15109MiB |     36%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:3B:00.0 Off |                  Off |
| N/A   44C    P0    29W /  70W |  14296MiB / 16127MiB |     39%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:86:00.0 Off |                  Off |
| N/A   44C    P0    62W /  70W |  14296MiB / 16127MiB |     39%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   45C    P0    63W /  70W |  13400MiB / 15109MiB |     39%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by merrymercy** [comment]
Depends on the current parallelization strategy. Adding more nodes adds more pipeline stages. This can hurt the latency.

https://github.com/alpa-projects/alpa/blob/dec88ed956d8800bef33ada423b1a761233a58f4/examples/opt_serving/model/wrapper.py#L336-L339
