### ISSUE TITLE
inference of opt-30b model with alpa Stop halfway

### ISSUE THREAD

**Issue by ganchaofan0000** [alpa-projects/alpa#613]
![image](https://user-images.githubusercontent.com/48487788/179461935-b8a86680-8775-459e-a530-405bceea2f02.png)
like the image ,gpu 0,1,2,3    gpu 4,5,6,7 utilization is different
and last stop but inference not finished

**Comment by ganchaofan0000** [comment]
i do not get any error when inference stop, but i find error when i run the python3 -m alpa.test_install
as follows
<img width="1666" alt="企业微信截图_16581462604977" src="https://user-images.githubusercontent.com/48487788/180009720-524427af-4a02-4326-9766-2cc587517527.png">
Environment used:
 8 V100 32 GB GPU,
CUDA: 11.1,
Cudnn: 8.0.5,
Driver Version: 450.156.00
Python: 3.7

**Comment by merrymercy** [comment]
Yeah, we should pass `python3 -m alpa.test_install` first. Could you refer to the tips at https://alpa.ai/install.html#unhandled-cuda-error?

**Comment by zhisbug** [comment]
@ganchaofan0000 This is a CUDA/GPU driver issue. Try re-install your driver and CUDA and pass the `test_install`

**Comment by ganchaofan0000** [comment]
ok, tanks!

**Comment by merrymercy** [comment]
closed due to inactivity
