### ISSUE TITLE
~5x slower down when adding one more node

### ISSUE THREAD

**Issue by JiahaoYao** [alpa-projects/alpa#621]
training mnist using **one node (4 T4-gpu)** is way faster than using **two nodes (4 T4-gpu each)**.

**Comment by JiahaoYao** [comment]
the video link is here: 
https://drive.google.com/file/d/1a4PJDwJXdhBsnFUX-Fbc8RJYflBry_bf/view?usp=sharing

**Comment by JiahaoYao** [comment]
my ray cluster is 
```python
(tensorflow2_p38) ubuntu@ip-10-0-2-92:~/alpa/examples/mnist$ ray status
======== Autoscaler status: 2022-07-21 18:33:27.553114 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray.worker.default
 1 ray.head.default
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/96.0 CPU
 0.0/8.0 GPU
 0.0/2.0 accelerator_type:T4
 0.00/254.908 GiB memory
 0.00/111.342 GiB object_store_memory

Demands:
 (no resource demands)
```


the difference of the two trails are with and without 
```python
alpa.init('ray')
```

**Comment by JiahaoYao** [comment]
my expectation is using one more node should be at least not slower.

**Comment by zhisbug** [comment]
what is the strategy used in 1 node and in 2 nodes?

**Comment by merrymercy** [comment]
This is mainly because the MNIST network is too small and the driver overhead dominates.

Some tips on how to reduce driver overhead 
- https://alpa.ai/tutorials/perf_tuning_guide.html#reducing-runtime-overhead
- Use a better data loader with prefetching

**Comment by merrymercy** [comment]
I tried the example and found there might be some bugs in the settings of the default mesh shape. I will fix it soon and make both imagenet/mnist example scalable on two nodes

**Comment by JiahaoYao** [comment]
oh, thanks @merrymercy @zhisbug . Appreciate it!

**Comment by JiahaoYao** [comment]
tag: https://github.com/alpa-projects/alpa/pull/630
