### ISSUE TITLE
adding the tutorial on the alpa documentation. 

### ISSUE THREAD

**Issue by JiahaoYao** [alpa-projects/alpa#622]
it would be good to add https://sites.google.com/view/icml-2022-big-model/ to the website, because hard to find this good website. 
ideally, i would like to put it here (
<img width="520" alt="image" src="https://user-images.githubusercontent.com/20907377/180289141-cf541b98-5581-415b-9538-2d64532e1b34.png">
)

but not sure how to put here (
<img width="459" alt="image" src="https://user-images.githubusercontent.com/20907377/180289356-182726f6-4d40-49df-b057-06b795fc9ab4.png">
)

**Comment by zhisbug** [comment]
There is a ticket in Linear assigned to @merrymercy to do that; maybe we can add you to the linear?

**Comment by merrymercy** [comment]
https://github.com/alpa-projects/alpa/pull/624
