### ISSUE TITLE
How to run the pipeline_parallel/test_stage_construction.py with two machines?

### ISSUE THREAD

**Issue by kevinsouthxu** [alpa-projects/alpa#627]
I have two machines which have different locations. I use the
```shell
ray start --head
```
at the first machine whitch has alpa. and I use the 
```shell
ray start --address=xxx.xxx.xxx.xxx:6379
```
at the second machine to connect the first machine..
At last I add 
```python
ray.init()
alpa.init(cluster="ray")
```
in the pipeline_parallel/test_stage_construction.py.
But the test results show that only the first machine was considered.

**Comment by kevinsouthxu** [comment]
I change the 
```python
ray.init()
```
to
```python
ray.init("localhost:6379")
```
and delete the alpa.init(cluster="ray")
now it outputs the information with:
```shell
(pid=gcs_server) [2022-07-24 03:37:10,162 E 32020 32020] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: failed to connect to all addresses; RPC Error details:
```

**Comment by zhisbug** [comment]
It seems your ray cluster isn't set up correctly. Please use `ray status` and check if the resources are right.

**Comment by kevinsouthxu** [comment]
> It seems your ray cluster isn't set up correctly. Please use `ray status` and check if the resources are right.


ray status outputs
```shell
======== Autoscaler status: 2022-07-24 04:04:22.326167 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_10635928e115297b1da2479fc2c4816a76e41c4ae2c07eb3c37c53a9
 1 node_f43e08d6fd498c113076708c39d3f8b8d1761d00a0914e20e169b033
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/32.0 CPU
 0.0/4.0 GPU
 0.0/1.0 accelerator_type:V100
 0.00/157.678 GiB memory
 0.00/71.568 GiB object_store_memory

Demands:
 (no resource demands)
```
two nodes both have 4GPUs and it seems that it thinks two nodes are both healthy

**Comment by zhisbug** [comment]
Does your entire cluster have 8 GPUs? But below it shows you only have 4 GPUs

**Comment by kevinsouthxu** [comment]
> Does your entire cluster have 8 GPUs? But below it shows you only have 4 GPUs

both machines have 4 GPUs and both two machines can connect the GPU with
```'shell
nvidia-smi
```
and they all install cuda11.1 with cudnn8.0.5
but it really confuses me that the node status show only 4GPUs

**Comment by kevinsouthxu** [comment]
> Does your entire cluster have 8 GPUs? But below it shows you only have 4 GPUs

its weird that when I only start the head node with
```shell
ray start --head
```
i can visit the dashboard at port 8265
but when I connect another node to this head node, the dashboard can't load the page and I can't see anything

**Comment by zhisbug** [comment]
Maybe check this guide to setup Ray: https://docs.ray.io/en/latest/cluster/cloud.html#manual-cluster

**Comment by kevinsouthxu** [comment]
> Maybe check this guide to setup Ray: https://docs.ray.io/en/latest/cluster/cloud.html#manual-cluster

I directly clone the latest alpa on two different machine and connect the with Ray. And it works
but when i change some codes of alpa and push it to a new repository and clone this repository into different two machines. The ray cannot work.
So I wonder whether there's some relationship about this process

**Comment by zhisbug** [comment]
@kevinsouthxu Maybe your two machines are running different versions of Ray? But glad to see your issue has a way to be resolved.

**Comment by kevinsouthxu** [comment]
> @kevinsouthxu Maybe your two machines are running different versions of Ray? But glad to see your issue has a way to be resolved.

I think its a network issue, which a machine in Japan cannot connect a machine in US.
I solve this issue by opening two machines in us-west.
