### ISSUE TITLE
jax._src.traceback_util.UnfilteredStackTrace: KeyError: Actor(MeshHostWorker, 5c9e360772b5c356485ec37003000000)

### ISSUE THREAD

**Issue by TonyTangYu** [alpa-projects/alpa#640]
**Please describe the bug**
I install Alpa and jaxlib from source code. When I run the `test_install.py` file,  it gives me the following error:
`jax._src.traceback_util.UnfilteredStackTrace: KeyError: Actor(MeshHostWorker, 5c9e360772b5c356485ec37003000000)`
**Please describe the expected behavior**

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker):
- Python version: 3.7
- CUDA version: 11.1
- NCCL version: 2.8.4
- cupy version: cupy-cuda111-11.0.0
- GPU model and memory: A100
- Alpa version: 0.0.0
- TensorFlow version:
- JAX version:

**Screenshots**
<img width="1122" alt="WeChatf5400969a12b29049c770d142c79aa65" src="https://user-images.githubusercontent.com/35730902/183448081-b39ffc27-e961-4e7a-8b65-686b1e70f89f.png">

**Comment by zhuohan123** [comment]
Does this bug occur consistently? Are there any other error messages above?

**Comment by zhuohan123** [comment]
Close this issue due to inactivity. Please re-open the issue to add more.
