### ISSUE TITLE
IndexError: `InlinedVector::at(size_type) const` failed bounds check

### ISSUE THREAD

**Issue by TonyTangYu** [alpa-projects/alpa#642]
**Please describe the bug**
I install alpa from source code. When I run `test_install.py`,  it gives me the following error: `IndexError: InlinedVector::at(size_type) const failed bounds check`. It seems an error form absl. But, I tried several versions of absl, this error still occurs. I wonder how to fix it and whether this is an error from alpa.

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker):
- Python version:3.7
- CUDA version:11.1
- NCCL version:2.8.4
- cupy version:cupy-cuda111-11.0.0
- GPU model and memory: A100, 80GB
- Alpa version: 0.0.0

**Screenshots**
![截屏2022-08-09 10 03 39](https://user-images.githubusercontent.com/35730902/183547508-1dcc3dde-597e-46d7-8e05-9580ebbe345c.png)

**Comment by zhuohan123** [comment]
How did you build your Jaxlib?

**Comment by zhuohan123** [comment]
Close this issue due to inactivity. Please re-open the issue to add more.
