### ISSUE TITLE
Dynamic batching for interactive serving needs an extra request

### ISSUE THREAD

**Issue by vinlnx** [alpa-projects/alpa#644]
When setting `MAX_BS` in constants.py to a value n (e.g., n=2), it takes n+1 requests to dispatch the batch.  Happens on the main branch.  You can reproduce by:

1. setting `MAX_BS` to a small value and `TIMEOUT_MS` to a large value
2. Starting up interactive serving
3. Submitting `MAX_BS` requests and waiting

**Comment by merrymercy** [comment]
Fixed in #669
