### ISSUE TITLE
Generation error

### ISSUE THREAD

**Issue by roblox34** [alpa-projects/alpa#649]
Generation error
English: Minecraft server is gone.
Japanese:  Minecraft server is gone.
Chinese: Minecraft server is gone.
Korean: Minecraft server is gone.
Russian: Minecraft server is gone.
Spanish: Minecraft server is gone.
French: Minecraft server is gone.
German: Minecraft server is gone.
Italian: Minecraft server is gone.
Port

**Comment by zhisbug** [comment]
@roblox34 thanks for reporting issues -- could you tell us what is your prompt?

**Comment by roblox34** [comment]
> @roblox34 thanks for reporting issues -- could you tell us what is your prompt?

English: Minecraft server is gone.
Japanese:

**Comment by zhisbug** [comment]
@roblox34 You can try to extend the prompt to give it an example translation

**Comment by zhisbug** [comment]
@roblox34 I don't think OPT-175B is able to do such an open-ended translation from English to Japanese. You can try to tune your prompt a bit to give a longer context.
