### ISSUE TITLE
Error that seems to be related to HTML

### ISSUE THREAD

**Issue by jmouchnino** [alpa-projects/alpa#651]
After prompting a second prompt, there's an error message

When I enter a first prompt, it does generate a text. But a second prompt produces an error 

**Screenshots**
![Screenshot_2022-08-13-14-02-17-103_com.android.chrome.jpg](https://user-images.githubusercontent.com/103758616/184493293-71005819-b8e1-4d46-8bd0-d2094e3e257d.jpg)

**Comment by zhisbug** [comment]
@jmouchnino Thanks for reporting! Fixing it now!

**Comment by zhisbug** [comment]
@jmouchnino fixed.
