### ISSUE TITLE
Got 403 Forbidden Error on Alpa-OPT website

### ISSUE THREAD

**Issue by infwinston** [alpa-projects/alpa#660]
**Please describe the bug**

On the Alpa-OPT [website](https://opt.alpa.ai/), some weird 403 error is triggered by a specific prompt "`report like the`".

**Please describe the expected behavior**

Expected behavior would be generating a normal sequence starting with "`report like the`".

**To Reproduce**
1. Input `report like the` in the prompt.
2. Hit "Generate" and see below error.
```
    <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Screenshots**
![my-opt175b-result (2)](https://user-images.githubusercontent.com/1206058/185538945-3bc56b79-9738-4a0f-88b0-3458506f7ec7.png)

**Comment by zhisbug** [comment]
@infwinston yeah we're aware of this issue and are looking into it.

**Comment by zhisbug** [comment]
@infwinston fixed!
