### ISSUE TITLE
[OPT Serving] Expose other results with RESTful API

### ISSUE THREAD

**Issue by JetRunner** [alpa-projects/alpa#673]
Hi, I see the comment here: https://github.com/alpa-projects/alpa/blame/main/examples/opt_serving/service/responses.py#L27

I wonder if you can simply expose all the output from HF transformers (since they're already passed to the response function anyway)? It could be very helpful for NLP research. It doesn't have to align with GPT-3 API.

**Comment by merrymercy** [comment]
Good suggestions. We love to hear your use cases! I sent you an invite to join our slack channel about opt-as-a-service.
