### ISSUE TITLE
OOM error on a 384 VRAM GB 8x RTX A6000

### ISSUE THREAD

**Issue by saisurbehera** [alpa-projects/alpa#680]
OOM error on a 384 VRAM GB 8x RTX A6000

**System information and environment**
- OS Platform and Distribution : Linux Ubuntu 1804
- Python version: 3.8.10 
- CUDA version: 11.2
- NCCL version:
- cupy version: 11.2
- GPU model and memory: 8x RTX A6000 

<img width="761" alt="image" src="https://user-images.githubusercontent.com/42232832/187079051-f92d0992-e216-4be6-8c9b-9db2002b5d56.png">
<img width="709" alt="image" src="https://user-images.githubusercontent.com/42232832/187079087-4e32fba5-b1fa-4b46-b781-11329c36e0a9.png">

**Comment by merrymercy** [comment]
Hi, did you solve your problem?

**Comment by merrymercy** [comment]
closed due to inactivity
