### ISSUE TITLE
jaxlib-0.3.5 not found but listed in https://alpa.ai/wheels.html

### ISSUE THREAD

**Issue by cokuehuang** [alpa-projects/alpa#692]
**Please describe the bug**
Installed jaxlib-0.3.5+cuda113.cudnn820-cp38 before, but now I want to get it at https://alpa.ai/wheels.html, resource not found.
**Please describe the expected behavior**

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker):
- Python version:
- CUDA version:
- NCCL version:
- cupy version:
- GPU model and memory:
- Alpa version:
- TensorFlow version:
- JAX version:

**To Reproduce**
1.
2.
3.

**Screenshots**

**Code snippet to reproduce the problem**

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by merrymercy** [comment]
Hi, our index only saves the latest version. The latest version is `alpa==0.2.0` and `jaxlib==0.3.15` (https://alpa.ai/install.html#method-1-install-from-python-wheels).

If you want to install the older version, you can still find the wheel the assets sections of our old releases (https://github.com/alpa-projects/alpa/releases)
