### ISSUE TITLE
install jaxlib==0.3.5 broken

### ISSUE THREAD

**Issue by OrenLeung** [alpa-projects/alpa#695]
`pip install jaxlib==0.3.5+cuda113.cudnn820 -f https://alpa-projects.github.io/wheels.html`

results in an error as `https://github.com/alpa-projects/alpa/releases/download/v0.2.0/jaxlib-0.3.5%2Bcuda113.cudnn820-cp38-none-manylinux2010_x86_64.whl` does not exist

fix:  change to `https://github.com/alpa-projects/alpa/releases/download/v0.1.6/jaxlib-0.3.5%2Bcuda113.cudnn820-cp38-none-manylinux2010_x86_64.whl`

for jaxlib==0.3.5 versions

workaround: `pip install jaxlib==0.3.5+cuda113.cudnn820 -f https://github.com/alpa-projects/alpa/releases/download/v0.1.6/jaxlib-0.3.5%2Bcuda113.cudnn820-cp38-none-manylinux2010_x86_64.whl`

**Comment by zhisbug** [comment]
@OrenLeung : please use jaxlib==0.3.15 instead

**Comment by merrymercy** [comment]
duplication of https://github.com/alpa-projects/alpa/issues/692

**Comment by merrymercy** [comment]
Duplication of https://github.com/alpa-projects/alpa/issues/692.

Thanks for sharing the fix. That is the recommended way to install old versions.
