### ISSUE TITLE
Question: what is the overhead of these collectives?

### ISSUE THREAD

**Issue by OrenLeung** [alpa-projects/alpa#697]
What is the overhead of transforming cupy tensor to jax tensor? is this zero copy operation or is there copying of the buffers involved? If so, is it zero copy for both directions?

https://github.com/alpa-projects/alpa/blob/main/alpa/collective/worker_nccl_util_cupy.py#L68-L128

Thanks in advance <3

**Comment by zhisbug** [comment]
@OrenLeung No overhead. It is zero-copy

**Comment by OrenLeung** [comment]
@zhisbug thanks for answering :)
