### ISSUE TITLE
Converting OPT-175B requires more than 700Gb of memory

### ISSUE THREAD

**Issue by asolano** [alpa-projects/alpa#702]
Greetings,

According to the documentation [1] it should take around 700Gb of memory to run the `step_2_consolidate_992_shards_to_singleton.py` script, but when trying to run it on a cluster node with a set limit of 800Gb it resulted in the process being killed with an OOM error message. 

The administrators have confirmed in the logs that the job process consumed all its assigned memory and recommended to change the script to reduce its memory usage.

Is the documentation estimate of peak memory inaccurate or is there some extra option that needs to be set to run the script to completion?

For reference, the job log is:

```
100%|██████████| 992/992 [41:45<00:00,  2.53s/it]  
- Part 1: consolidate Zero-3 shards.
100%|██████████| 8/8 [03:16<00:00, 24.52s/it]/var/spool/uge/execd/m01/job_scripts/10505862: line 18: 16348 Killed                  python3 step_2_consolidate_992_shards_to_singleton.py --read-prefix /groups/gcb50389/datasets/OPT175B/shards/checkpoint_last --save-prefix /groups/gcb50389/datasets/OPT175B/consolidated_1/
```

Thanks,

Alfredo 

[1] https://alpa.ai/tutorials/opt_serving.html#convert-opt-175b-weights-into-alpa-formats

**Comment by zhisbug** [comment]
@asolano Have your figured out a solution? On our machines 700GB of memory is sufficient.

**Comment by asolano** [comment]
Hi Hao, thanks for your interest. We tried a couple more times to see if it was a problem of the node but the results did not change.

So, in the end we found a local machine with decent memory (512G) and network shared storage and asked the administrator to create an additional swapfile just for the conversion (384G, I think). We ran both steps on that machine, and as expected it took quite a while.

For reference:
```
python3 step_2_consolidate_992_shards_to_singleton.py --read-prefix  ~/shards/checkpoint_last --save-prefix ~/consolidated
...
    key: decoder.layers.95.self_attn_layer_norm.weight, shape: torch.Size([12288])
    key: decoder.layers.95.self_attn_layer_norm.bias, shape: torch.Size([12288])
    key: decoder.layers.95.fc1.weight, shape: torch.Size([49152, 12288])
    key: decoder.layers.95.fc1.bias, shape: torch.Size([49152])
    key: decoder.layers.95.fc2.weight, shape: torch.Size([12288, 49152])
    key: decoder.layers.95.fc2.bias, shape: torch.Size([12288])
    key: decoder.layers.95.final_layer_norm.weight, shape: torch.Size([12288])
    key: decoder.layers.95.final_layer_norm.bias, shape: torch.Size([12288])
    key: decoder.version, shape: torch.Size([1])
Done consolidating after 1636004802.2552793 minutes
- Saving to /home/asolano/consolidated.pt ...
Done saving after 246.0 minutes
```

(The time calculation looks.. suspicious)

And then for the conversion to numpy:
```
python3 step_3_convert_to_numpy_weights.py --ckpt-path ~/consolidated --output-folder ~/opt_alpa/
...
- Writing tensor decoder.layers.95.self_attn.out_proj.bias with shape torch.Size([12288])
- Writing tensor decoder.layers.95.self_attn_layer_norm.weight with shape torch.Size([12288])
- Writing tensor decoder.layers.95.self_attn_layer_norm.bias with shape torch.Size([12288])
- Writing tensor decoder.layers.95.fc1.weight with shape torch.Size([49152, 12288])
- Writing tensor decoder.layers.95.fc1.bias with shape torch.Size([49152])
- Writing tensor decoder.layers.95.fc2.weight with shape torch.Size([12288, 49152])
- Writing tensor decoder.layers.95.fc2.bias with shape torch.Size([12288])
- Writing tensor decoder.layers.95.final_layer_norm.weight with shape torch.Size([12288])
- Writing tensor decoder.layers.95.final_layer_norm.bias with shape torch.Size([12288])
- Writing tensor decoder.version with shape torch.Size([1])
```

(It took another few hours)

Just in case it is useful to someone, here is the MD5 of the consolidated file:

```
md5sum  /groups/gcb50389/datasets/OPT175B/consolidated_1/consolidated.pt 
6e86e8eb27917e254ea20d7967de295f  /groups/gcb50389/datasets/OPT175B/consolidated_1/consolidated.pt
```

Thanks again,

Alfredo

**Comment by zhisbug** [comment]
@asolano the time taken on write does not look normal to me. On my EC2 instance, the write takes < 30mins. I suspect that writing to your network FS might have a bottleneck, But glad to know it eventually work.
