### ISSUE TITLE
The program blocks when inference

### ISSUE THREAD

**Issue by zd11024** [alpa-projects/alpa#709]
**Please describe the bug**
The process blocks when inference with opt-6.7b. I adapt the example program to my custom datasets, just some simple iterations. The first several iterations could run successfully. And I observed that the GPU utilization of first 4 GPUs suddenly changed to 100%, while the other 4 GPUs to 0% (see the following Figure). In addition, I have passed the "python -m alpa.test_install" test.

**Please describe the expected behavior**
the process runs successfully.

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Linux
- Python version: 3.7.13
- CUDA version: 11.1
- NCCL version: 2.10.3
- cupy version: 11.1.0
- GPU model and memory: Nvidia A100 80G * 8
- Alpa version: 0.2.0
- TensorFlow version:
- JAX version: 0.3.15

**To Reproduce**
1. modify the code "examples/llm_serving/textgen.py"
2. start a new session with tmux. then run "ray start --head" and the code.
3. first several iterations successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/34681526/190952528-f104021b-9ef4-4704-bc72-fc5cb446111e.png)

**Code snippet to reproduce the problem**

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by merrymercy** [comment]
Did you install alpa by wheel or build from source? This kind of error typically comes from nccl deadlock.
1. There is an experimental feature in alpa to not use cupy.nccl . Change this [line](https://github.com/alpa-projects/alpa/blob/25ea228aab414b9741caf919898b1fa577c6244d/alpa/global_env.py#L65) in alpa source code (get the location of source code by python3 -c "import alpa; print(alpa.__path__)" to self.nccl_mode = "xla_extension" . Try to run python3 -m alpa.test_install again.
2. Try to build alpa from source

**Comment by zd11024** [comment]
Thanks for your reply! I have tried both 1 and 2, but the problem still happens. Are there any other methods?

**Comment by merrymercy** [comment]
Sorry, I don't have any good ideas.
You can try to update Cuda driver and re-install cupy/nccl/cuda from a clean environment/container.

**Comment by zhisbug** [comment]
@zd11024 have you fixed the error?
