### ISSUE TITLE
How to specify the gcc version used to build and install jaxlib without root authority? 

### ISSUE THREAD

**Issue by DicardoX** [alpa-projects/alpa#710]
**System information**
- Alpa version:

alpa-1.0.0.dev0

- Are you willing to contribute it (Yes/No):

Yes

**Describe the new feature and the current behavior/state**

As the documentation of Alpa says, gcc=9.4 will cause a compilation error, which I indeed encountered. I want to switch my gcc version to 7.5 as recommended, but unfortunately I don't have the root authority. It seems that Bazel can build with specified gcc version, so what can I do to? Thx!

**Will this change the current API? How?**

**Describe alternatives you've considered**

**Additional context**

**Comment by DicardoX** [comment]
I have tried commands like:

cc=/usr/bin/gcc-7 python3 build/build.py --enable_cuda --dev_install --bazel_options=--override_repository=org_tensorflow=$(pwd)/../third_party/tensorflow-alpa --bazel_options=--action_env=cc

which aims to use '--action_env' to pass the env variable cc=/usr/bin/gcc-7 to Bazel, but still don't work...

Here is my error report:

[0 / 897 [Prepa] BazelWorkspaceStatusAction stable-status.txt
(8 actions, 0 running)
[2,381 / 13,025] Compiling src/cpu/cpu_convolution_list.cpp;34s local ... (40 actions, 38 running)
[3,551 / 13,025] Compiling tensorflow/compiler/xla/service/cpu/runtime_matmul.cc; 74s local
(40 actions, 39 running)
[5,556 / 13,111] Compiling tensorflow/compiler/xla/service/cpu/runtime_matmul.cc;159slocal
(40 actions, 39 running)
[6,235 / 13,111] Compiling mlir/lib/Dialect/SPIRV/IR/SPIRVOps.cpp;83slocal
(40 actions,
39 running)
[8,705 / 13,181] Compiling 11vm/lib/Transforms/Vectorize/LoopVectorize. cpp; 33s local
... (40 actions, 39 running)
[9,320 / 13,181] Compiling mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp;79slocal
.. (40 actions, 39 running)
[11,729 / 13,181] Compiling 1lvm/lib/Target/X86/X86ISelLowering.cpp; 785 local
(40 actions, 39 running)
ERROR: /home/cyxue/.cache/bazel/_bazel_cyxue/7f0d3638ac6ebab783173044f28f4f4d/external/org_tensorflow/tensorflow/compiler/xla/service/BUILD:
6736:11: Compiling tensorflow/compiler/xla/service/pass_context.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (cd/home/cyxue/.cache/bazel/_bazel_cyxue/7f0d3638ac6ebab783173044f28f4f4d/execroot/__main__ && \
exec env -
LD_LIBRARY_PATH=/usr/local/cuda/lib64: PATH=/home/cyxue/miniconda3/envs/jax_framework/bin:/home/cyxue/miniconda3/condabin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/proc/self/cwd
TF_CUDA_COMPUTE_CAPABILITIES=sm_35,sm_52,sm_60,sm_70,compute_80\
TF_NCCL_VERSION=2.14.3\
external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc-MD-MFbazel-out/k8opt/bin/external/org_tensorflow/te

**Comment by zhisbug** [comment]
@DicardoX  try these two lines? 

https://github.com/alpa-projects/alpa/blob/main/docker/scripts/build_jaxlib_docker_entrypoint.sh#L10-L11

**Comment by DicardoX** [comment]
> @DicardoX try these two lines?
> 
> https://github.com/alpa-projects/alpa/blob/main/docker/scripts/build_jaxlib_docker_entrypoint.sh#L10-L11

You mean commands like these?

export CC=/usr/bin/gcc-7 
export GCC_HOST_COMPILER_PATH=/usr/bin/gcc-8
python3 build/build.py --enable_cuda --dev_install --bazel_options=--override_repository=org_tensorflow=$(pwd)/../third_party/tensorflow-alpa

**Comment by DicardoX** [comment]
@zhisbug Thx, it works!!
