### ISSUE TITLE
pip install alpa takes a long time

### ISSUE THREAD

**Issue by de1star** [alpa-projects/alpa#719]
Hi, alpa group! I'd like to try your great work on my cluster, but pip install alpa took a lot of time and I still did not finish it.
![image](https://user-images.githubusercontent.com/37529028/192496537-325ca9dc-f44f-4e1e-bfb7-8cb141eec9a0.png)
I found during the pip, different versions of a package would be collected and it was time-consuming. Would you like to provide some suggestions?

INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime.
Should I provide some version constraints during piping install alpa?

**Comment by zhisbug** [comment]
Hi @de1star, thanks for your interest on Alpa. 

I just did a test on my local dev PC using a virtual env with an HDD.

Installing alpa via `pip install alpa` takes ~48 seconds on my PC.  
Installing jaxlib-alpa via `pip3 install jaxlib==0.3.15+cuda111.cudnn805 -f https://alpa-projects.github.io/wheels.html` takes ~24 seconds. 
In total, it takes 72 seconds.

As a comparison, `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` takes ~2min18s.

I think for Alpa, the installation time is good enough. 

Sometimes if one puts the Python environment on some NFS system like AWS EFS or has weak connections to the pypi index, slowness will be observed.

**Comment by Jack47** [comment]
the log shows incursively installing urllib, maybe we can manually install urllib first then pip install alpa?
