### ISSUE TITLE
ray.exceptions.RayTaskError(NcclError): ray::MeshHostWorker.init_p2p_communicator() in every ray runtime.

### ISSUE THREAD

**Issue by Yu-gyoung-Yun** [alpa-projects/alpa#730]
Hello. Thanks for providing the alpa project.
I'm new to this type of projects so I'm trying to follow this works.

But when I run the 'ray related code ( which contains ray.init(~))', It prints error like below:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/74442792/194075885-b96b80ec-f85b-4c92-8d0f-ccac4a8bde3c.png">
Error was from: alpa/docs/gallery/tutorials/pipeshard_parallelism.py

However, When I try to execute the another code like the quickstart.py(Shard_parallel using alpa.init(cluster='local') ), they works well. 
I think local execution code w/o ray works well for me. (local other code in folder shard_parallel works well.)

SO, I want to ask two things.
1. ray error solution (above image)
2. I want to execute the PipeShardParallel in my local device(alpa.init(cluster='local')). But it seems like PipeShardParallel is only supported by ray env. Is there any way to run pipeshardparallel on Local?

**System information and environment:**
I installed the project through alpa docker file as you mentioned in alpa/docker README.md. and all the code was executed in this container. So, all the envrionment is same as the latest alpa docker file.

OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Ubuntu 20.04
Python version: 3.8.13
CUDA version: 11.3
![image](https://user-images.githubusercontent.com/74442792/194011213-1a1a4208-9c6c-4f84-9d0e-0b03219344cb.png)

NCCL version: 2.10.3
cupy version: 11.1.0
GPU model and memory: RTX 3090
Alpa version: 0.2.1
TensorFlow version: 2.10.0
JAX version: 0.3.15
JAXlib version: 0.3.15+cuda113.cudnn820

- another info:
![image](https://user-images.githubusercontent.com/74442792/194015356-6fe2a9ff-f609-4b6b-b943-624bdc8b41af.png)

Thanks for reading and your effort.
I really want to run this code..

**Comment by merrymercy** [comment]
This is a common error. The root source is this error "cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_UNHANDLED_CUDA_ERROR: unhandled cuda error"
This page has some helpful information
https://alpa.ai/install.html#unhandled-cuda-error

**Comment by Yu-gyoung-Yun** [comment]
Thanks for answering.
I also read that but it didn't work for my case so I guess it was a different problem.
After that, I tired to re-configure the setting of cuda, cudnn, etc and finally I solved it in following way.

First of all, I add code "import os os.environ["NCCL_DEBUG"] = "INFO" in pipeshard_parallelism.py.
output: 
<img width="792" alt="image" src="https://user-images.githubusercontent.com/74442792/194453547-29b40317-519c-450d-9146-dd3740deb013.png">

according to this msg, I found it is related to "nccl_p2p issue".

Second, add code "os.environ["NCCL_P2P_DISABLE"] = "1" " in pipeshard_parallelism.py.

ref:
https://stackoverflow.com/questions/66807131/how-to-solve-the-famous-unhandled-cuda-error-nccl-version-2-7-8-error

**Comment by Yu-gyoung-Yun** [comment]
According to code analysis,
I think the class pipeshard parallel method can only be used in the ray environment now, but I wonder if you have any intention of supporting the pipeshard parallel method in local in the future. or Is there any way to run PipeShardParallel in local w/o ray?

**Comment by zhuohan123** [comment]
We use ray mainly for easy management of distributed actors and control plane communication. Technically Alpa should be able to run without ray but we don't see a better alternative to ray for these functions now. Is there any particular reason that you cannot use ray in your environment?

**Comment by merrymercy** [comment]
It is not about ray. As you found, your problem is mainly caused by nccl point-to-point communication.
If you want to do real pipeline parallelism, nccl is a must. I don't know your use cases, but here this is a fake local pipeline runtime, maybe it is useful to you.

https://github.com/alpa-projects/alpa/blob/cfa8b86521efed68ff437d0419f9e2e7c8ad67fe/tests/pipeline_parallel/test_mlp.py#L71

**Comment by Yu-gyoung-Yun** [comment]
I'm not used to ray, so I was wondering if I could turn it to local efficiently. Thank you for your answer.
