### ISSUE TITLE
Make `tokenizer_name` configurable in `llm_serving`

### ISSUE THREAD

**Issue by zhanyuanucb** [alpa-projects/alpa#734]
**System information**
- Alpa version: v0.2.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the new feature and the current behavior/state**
`tokenizer_name` should be configurable. Currently, it defaults to `facebook/opt-30b`

**Will this change the current API? How?**
The script `launch_model_worker.py` will have one more optional argument `--tokenizer`

**Describe alternatives you've considered**

**Additional context**

**Comment by zhuohan123** [comment]
Hi Sean! Thanks for helping out on this. Let us know if you met any issues.
