### ISSUE TITLE
`llm_serving` not compatible with `transformers 4.23.1`

### ISSUE THREAD

**Issue by zhanyuanucb** [alpa-projects/alpa#741]
**Please describe the bug**
`llm_serving` not compatible with `transformers 4.23.1`. Here is the trace:
```
(DeviceMeshGroupManager pid=69681) Traceback (most recent call last):
(DeviceMeshGroupManager pid=69681)   File "launch_model_worker.py", line 128, in batch_loop
(DeviceMeshGroupManager pid=69681)     results = self.generator.generate(**args)
(DeviceMeshGroupManager pid=69681)   File "/home/zhanyuan.zhang/alpa/examples/llm_serving/generator.py", line 175, in generate
(DeviceMeshGroupManager pid=69681)     output_ids = self.model_wrapper.generate(input_ids=input_ids, **generator_args)
(DeviceMeshGroupManager pid=69681)   File "/home/zhanyuan.zhang/.conda/envs/alpa-debug/lib/python3.8/site-packages/transformers/generation_utils.py", line 734, in _get_logits_processor
(DeviceMeshGroupManager pid=69681)     suppress_tokens = suppress_tokens if suppress_tokens is not None else self.config.suppress_tokens
(DeviceMeshGroupManager pid=69681) AttributeError: 'InferenceFuncConfig' object has no attribute 'suppress_tokens' 
```

**Please describe the expected behavior**

**System information and environment**
- OS Platform and Distribution: Linux Ubuntu 16.04:
- Python version: 3.8
- CUDA version: 11.1
- NCCL version: 2.10.3
- cupy version: cupy-cuda111==11.2.0
- GPU model and memory: (GeForce GTX 1080 Ti, 11GB)x2
- Alpa version: v0.2.1
- TensorFlow version: N/A
- JAX version: jax==0.3.15, jaxlib==0.3.15+cuda111.cudnn805

**To Reproduce**
1. Follow [here](https://github.com/alpa-projects/alpa/tree/main/examples/llm_serving#requirements) to installation requirement
2. Check that `transformers 4.23.1` is installed
3. Go to `localhost:8001` and enter any prompt
4. See the error message from console

**Screenshots**

**Code snippet to reproduce the problem**
 To launch model worker: 
```
python launch_model_worker.py --model alpa/bloom-560m --path ~/bloom-560m_weights/ --host 127.0.0.1 --tokenizer bigscience/bloom-7b1
``` 
And to start the website: 
```
uvicorn launch_website:app --host 127.0.0.1 --port 8001
```

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by ddxxdd-code** [comment]
Just filed a PR to solve this: https://github.com/alpa-projects/alpa/pull/742
My textgen.py result after importing the changes in this PR:
<img width="682" alt="Screen Shot 2022-10-11 at 17 56 02" src="https://user-images.githubusercontent.com/65443542/195206290-e4fe1d39-e8bb-46f3-9e33-fda8b0e5a84b.png">
