### ISSUE TITLE
ROCm support?

### ISSUE THREAD

**Issue by OhadRubin** [alpa-projects/alpa#743]
Hey guys,
Just wanted to let you know about [this](https://github.com/illuhad/hipSYCL)  project, that might allow you to cross-compile alpa to AMD gpus.

**Comment by merrymercy** [comment]
Thanks for sharing the information. XLA also supports AMD gpus via ROCm, so this should be possible.
However, we don't have the bandwidth to do this and we don't have AMD GPUs in our hands either.
Community contribution is welcome.
