### ISSUE TITLE
KeyError in get_donatable_intermediate when doing grid_search_auto

### ISSUE THREAD

**Issue by Yu-gyoung-Yun** [alpa-projects/alpa#749]
Hello. Thanks for providing the alpa project.

When I run the "python3 benchmark.py --suite gpt.grid_search_auto" in single node(4 GPUs) with ray.
(For using the ray in my environment, I add the below code in benchmark.py)
![image](https://user-images.githubusercontent.com/74442792/196130347-f99abc58-211c-4da4-ada2-2bdf5759b83d.png)

The below error is occur.
![image](https://user-images.githubusercontent.com/74442792/196125411-556e0479-e8b0-490e-9f50-12d8b61f9943.png)
Error was from: alpa/benchmark/alpa/benchmark.py
and the KeyError is occured with different keyword like vko, sko, lk, etc.
![image](https://user-images.githubusercontent.com/74442792/196126040-ee6785a6-bd57-4340-8153-3f294a80af29.png)
![image](https://user-images.githubusercontent.com/74442792/196126112-b5375d6c-6cae-41d6-b1e0-919e5feec059.png)

When I print the `main_copy_at` and `stage_at`, the KeyError keyword is not in there both.
and every runtime the error words are different.

How to fix this error?
(Pipeshard_parallelism.py which uses `def get_donatable_intermediate` works well and there's no error in the same setting)

--------------------------------------------
System information and environment:
I installed the project through alpa docker file as you mentioned in alpa/docker README.md. and all the code was executed in this container. So, all the envrionment is same as the latest alpa docker file.

OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Ubuntu 20.04
Python version: 3.8.13
CUDA version: 11.3
NCCL version: 2.10.3
cupy version: 11.1.0
GPU model and memory: RTX 3090
Alpa version: 0.2.1
TensorFlow version: 2.10.0
JAX version: 0.3.15
JAXlib version: 0.3.15+cuda113.cudnn820

Thanks for reading and your effort.

**Comment by zhuohan123** [comment]
cc @ZYHowell. Is this related to #672?

**Comment by Yu-gyoung-Yun** [comment]
`manual_stage_option`: 
ManualStageOption(forward_stage_layer_ids=[[0], [1]], submesh_physical_shapes=((1, 2), (1, 2)), submesh_logical_shapes=[(1, 2), (2, 1)], submesh_autosharding_option_dicts=[{'force_batch_dim_to_mesh_dim': 0}, {}])

KeyError: sko
and I found that error keyword is in  `JaxPipelineComputation`(name='1_apply_grad', invars = [lk, ll, ... , sko, ...]).
'sko' is one of the invars in JaxPipelineComputation.
(Also, Other error keywords are in the same site(` JaxPipelineComputation(name = '1_apply_grad')` )

**Comment by merrymercy** [comment]
Maybe @ZYHowell can take a better look. But on p3.16xlarge, I can reproduce our old results without errors.

**Comment by zhuohan123** [comment]
I can run the same script on 4 GPUs with p3.8xlarge with no errors. Did you modify codes of Alpa? Can you re-install the latest `main` branch with the latest `tensorflow-alpa` and see whether the issue still exists?

**Comment by Yu-gyoung-Yun** [comment]
Thanks. Now I can solve my problems with installing the latest main branch.
