### ISSUE TITLE
Step-by-step instructions for serving opt-175b on alpa

### ISSUE THREAD

**Issue by zfchenUnique** [alpa-projects/alpa#751]
**System information**
- Alpa version: Latest
- Are you willing to contribute it (Yes/No): 
- Yes

**Describe the new feature and the current behavior/state**
I have only access to a slurm cluster with v100s. I wonder whether there is step-by-step instructions on setting up ray and alpa for using slurm. BTW, the following link for running ray with slurm seems to be broken.
https://alpa.ai/tutorials/opt_serving.html#:~:text=Before%20running%20the%20command%20below%2C%20start%20Ray%20on%20the%20cluster%20following%20this%20guide.%20You%20can%20check

**Will this change the current API? How?**
No,
**Describe alternatives you've considered**

**Additional context**

**Comment by zhisbug** [comment]
@zfchenUnique could you follow this tutorial to deploy Ray: https://docs.ray.io/en/master/cluster/vms/user-guides/community/slurm.html ?

**Comment by zhisbug** [comment]
@ddxxdd-code Per our conversation, your effort on Slurm will help address this issue.

**Comment by merrymercy** [comment]
closed due to inactivity
