### ISSUE TITLE
OPT-175B gets stuck on Larger Prompts

### ISSUE THREAD

**Issue by gulzainali98** [alpa-projects/alpa#769]
**Please describe the bug**
When doing multi gpu inference with OPT-175B model, it gets stuck at max_seq>512. I have tried 64,256,512 and 1024 tokens. It works at 512 Tokens but gets stuck forever at 1024 tokens. I am running it on 16 A100 40GB with 1400GB of ram and 64 CPUs. CPU usage remains minimal but after a certain point GPU utilization jumps to 100%  and stays there but no output is generated. 
**Please describe the expected behavior**
It should not get stuck

**System information and environment**
- Python version: 3.8
- CUDA version: 11.4
- NCCL version:
- cupy version:
- GPU model and memory: A100 40GB
- Alpa version: Latest
- TensorFlow version: Using Pytorch 1.9
- JAX version:

**To Reproduce**
1. Start Alpa OPT-175B with max_seq set to 1024
2. Allocate only 16 A100 GPUs. 
3. Run textgen.py script in llm_serving  
5. Wait forever.

**Comment by gulzainali98** [comment]
it gets stuck on Loading parameters. after we get this pirnt statement "Compile executables for encoder_chunk_sizes=[1, 64]. elapsed: 72.55 second."

**Comment by zhisbug** [comment]
@gulzainali98 Could you provide all your logs here, thanks

**Comment by gulzainali98** [comment]
@zhisbug https://drive.google.com/drive/folders/107el084zRPZByviB3EKADXXZCOXqNR32?usp=sharing
logs are present in both csv and json file. Look only at the field "message" in both files for the outputs.

**Comment by gulzainali98** [comment]
@zhisbug please let me know if anything is hinting towards possible problem in the logs?

**Comment by gulzainali98** [comment]
@zhisbug  these are the logs for 175B model. Upper were the 66B model. But we run into same problem with both models. For 66B,it's happening even at 64 max_return_tokens.
https://drive.google.com/file/d/1P_SQ8xUr117vVOceZhhqeHg9n1-EclX3/view?usp=sharing

**Comment by zhisbug** [comment]
@gulzainali98 why are your logs in JSON format? Do you have the logs in std outputs?

**Comment by zhisbug** [comment]
@gulzainali98 do you mind providing stdout log (instead of jsonified formats) so I can take a look? The current json log is very difficult to read.

**Comment by merrymercy** [comment]
closed due to inactivity
