### ISSUE TITLE
alpa should not depend on private functorch APIs

### ISSUE THREAD

**Issue by zou3519** [alpa-projects/alpa#770]
**Please describe the bug**

Hi, I am one of the developers for functorch. We're in the process of [refactoring functorch internals](https://github.com/pytorch/pytorch/pull/88756). I noticed that you're using private functorch APIs in alpa: https://github.com/alpa-projects/alpa/blob/4f1495528bcb26fcfffd9de51cc299b83bb0f7a0/alpa/torch/__init__.py#L69-L76, which our refactor will break.

There is an easier way to implement the `functorch_value_and_grad` function that is more robust:
```py
def functorch_value_and_grad(func, argnums, has_aux):
  fn = functorch.grad_and_value(func, argnums, has_aux)
  def wrapper(*args, **kwargs):
    grad, value = fn(*args, **kwargs)
    return value, grad
  return wrapper
```

**Comment by zhisbug** [comment]
@zou3519 Thanks for the information. 
@yf225 Could we just replace the `functorch_value_and_grad` using the suggested one above?

**Comment by merrymercy** [comment]
closed due to inactivity. We pause the development of the pytorch frontend
