### ISSUE TITLE
Why do I get this warning: This thread has been waiting for 10 seconds and may be stuck ?

### ISSUE THREAD

**Issue by TriLoo** [alpa-projects/alpa#778]
**Please describe the bug**

when I evaluate & save checkpoint of my model, looks like the thread has been stuck for a long time (already > 1h).

**Please describe the expected behavior**

I don't know how long it usually take to finish evaluating & saving models (~ 6.7B 's Model)

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Ubuntu 20.04
- Python version:3.8.13
- CUDA version:11.1
- NCCL version: 2804
- cupy version: cupy-cuda111
- GPU model and memory: V100, 32G * 32
- Alpa version: 0.2.1
- TensorFlow version: 2.10.0
- JAX version: 0.3.15

I set below environments:
XLA_PYTHON_CLIENT_PREALLOCATE=false
XLA_PYTHON_CLIENT_MEM_FRACTION=.99
XLA_PYTHON_CLIENT_ALLOCATOR=platform

use `tf.config.experimental.set_visible_devices([], "GPU")` in my python code.

**NCCL related environment vars**:
NCCL_INCLUDE_DIR=/usr/include
USE_SYSTEM_NCCL=1
NCCL_IB_TIMEOUT=20
NCCL_ASYNC_ERROR_HANDLING=1
NCCL_VERSION=2.8.2
NCCL_TREE_THRESHOLD=0
ITP_NCCL_BRANCH=bootstrap_tag
NCCL_TOPO_FILE=/opt/msft/topo.xml
NCCL_NET_GDR_LEVEL=5
NCCL_LIB_DIR=/usr/lib/x86_64-linux-gnu
NCCL_IB_PCI_RELAXED_ORDERING=1
NCCL_DEBUG=INFO
NCCL_SOCKET_INAME=eth0

**To Reproduce**

I use 32 V100 (32G) on 2 nodes to finetune Opt-6.7B, but the script stuck at model evaluation & saving.
1. download alpa repo
2. prepare finetune dataset
3. run_6.7b_shard.sh (from run_2.7b_shard.sh) in example/opt_finetune

**Screenshots**

**Code snippet to reproduce the problem**

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by merrymercy** [comment]
Could you successfully run the original `run_2.7b_shard.sh` without any modification?

**Comment by merrymercy** [comment]
closed due to inactivity
