### ISSUE TITLE
how can I know each operator is sharded?

### ISSUE THREAD

**Issue by harryhan618** [alpa-projects/alpa#780]
Sorry, May I ask how can I know each each operator is sharded? Is there some way to print them out? Could you share some example code?

And I'm also curious about how many sharding options do you have for an operator, e.g., matmul? How can I find it out in the source code?

Looking forward to your reply! Thx

**Comment by merrymercy** [comment]
>  how can I know each operator is shared?
You can print the HLO IR
You can use `print(hlo.to_string)` before and after this line https://github.com/alpa-projects/alpa/blob/90fc12ac1bf123f47fbe559a31455abb76e86ee7/alpa/shard_parallel/auto_sharding.py#L344

> And I'm also curious about how many sharding options do you have for an operator, e.g., matmul? How can I find it out in the source code?
All strategies for matmul are registered in this function
https://github.com/alpa-projects/tensorflow-alpa/blob/24d5f1b6db59fd19b289f1da3ff61e8869a2625f/tensorflow/compiler/xla/service/spmd/auto_sharding_dot_handler.cc#L327
