### ISSUE TITLE
Key Error for  buffer_dict

### ISSUE THREAD

**Issue by dumpmemory** [alpa-projects/alpa#797]
**Please describe the bug**

Then I tried to train a gpt-neo 1.3b  parameters model using the code https://github.com/alpa-projects/alpa/blob/main/examples/gpt2/run_clm_flax.py on 2 nodes, one head node which don't have any cpus or gpus and one worker node has 8 gpus showing the following error:
~~~
2022-12-02 14:31:03,423	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::MeshHostWorker.run_executable() (pid=8620, ip=10.32.10.64, repr=<alpa.device_mesh.MeshHostWorker object at 0x7fd3c60e67c0>)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/alpa/device_mesh.py", line 277, in run_executable
    self.executables[uuid].execute_on_worker(*args, **kwargs)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/alpa/mesh_executable.py", line 907, in execute_on_worker
    del buffer_dict[next_batches_uuids[i]]
KeyError: None
~~~

**Please describe the expected behavior**

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Docker based on nvidia/cuda:11.3.1-cudnn8-devel-centos7
- Python version: 3.8
- CUDA version: 11.3
- NCCL version: 820
- cupy version: cupy-cuda113
- GPU model and memory: 2080ti 11g
- Alpa version: 0.2.2
- TensorFlow version: 2.1.0
- JAX version: `0.3.22+cuda113.cudnn820`

**To Reproduce**

I have modified the https://github.com/alpa-projects/alpa/blob/75f3597dbf4a49debce3cc1a8c83f2cb7b8b6eda/alpa/device_mesh.py#L2153 line, to pass the node which don't have any gpus. 

Then I tried to train a gpt-neo 1.3b parameters model using the code https://github.com/alpa-projects/alpa/blob/main/examples/gpt2/run_clm_flax.py on 2 nodes, one head node which don't have any cpus or gpus and one worker node has 8 gpus(2080) using following command :
~~~
ray job submit --working-dir . --address http://10.32.13.122:8265 -- python run_clm_jax.py --output_dir="test_norwegian-gpt-neo_big"     --model_type="gpt-neo"     --config_name="pretrain_model/models--EleutherAI--gpt-neo-1.3B/snapshots/797174552ae47f449ab70b684cabcb6603e5e85e/"     --tokenizer_name="pretrain_model/models--EleutherAI--gpt-neo-1.3B/snapshots/797174552ae47f449ab70b684cabcb6603e5e85e/"     --dataset_name="oscar"     --dataset_config_name="unshuffled_deduplicated_no"     --do_train --do_eval     --block_size="512"     --per_device_train_batch_size="2"     --per_device_eval_batch_size="2"     --num_micro_batches="1"     --dtype="float16"     --learning_rate="1e-3" --warmup_steps="1000"     --adam_beta1="0.9" --adam_beta2="0.98" --weight_decay="0.01"     --overwrite_output_dir     --num_train_epochs="1"     --logging_steps="100"     --save_steps="2500"     --eval_steps="2500"
~~~

**Comment by ZYHowell** [comment]
Can you run `tests/pipeline_parallel/test_bert.py` successfully? Plus, I also wonder more detail of the KeyError, say, is `i == None` or `next_batches_uuids[i] == None`?

**Comment by dumpmemory** [comment]
yeah, I will check it

**Comment by dumpmemory** [comment]
> tests/pipeline_parallel/test_bert.py

This is passed the test

**Comment by samblouir** [comment]
I have been getting the same error. I had to reduce the VRAM usage, though there should have been plenty of it.

**Comment by dumpmemory** [comment]
> 

how did u do to reduce the vram usage

**Comment by dumpmemory** [comment]
> Can you run `tests/pipeline_parallel/test_bert.py` successfully? Plus, I also wonder more detail of the KeyError, say, is `i == None` or `next_batches_uuids[i] == None`?

I am back. After reproduce the error,  i found that i ==0 and next_batches_uuids[i] == None and next_batches_uuids ==(None,)
