### ISSUE TITLE
RayOutOfMemoryError in RAM during OPT finetune

### ISSUE THREAD

**Issue by cksmll** [alpa-projects/alpa#811]
**Please describe the bug**
Sorry for frequent issue (Because I'm new this kind of projects).
According to https://alpa.ai/tutorials/opt_serving.html, when running the OPT_66B model, it will approximately have a peak memory usage of 66B x 2 bytes x 2 = 264GB. 
And I have the total 377.81GB RAM in CPU and 8 GPUs (24 GB).

But when I run the OPT_66B model with alpa(using the script in alpa/example/opt_finetune/), Even before the actual GPU works, the OOM of CPU RAM displays as shown below. (Until the error, there's no GPU works found)
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/119835217/207521459-389ab52c-1674-4f94-8cbe-e3f313684aaa.png">
and here is my ray dashboard right before the OOM error.
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/119835217/207522798-fc64c6f8-2679-4a79-bcc2-dc9446576dc0.png">

I want to know why this is happen in alpa and how to fix it.
For OPT_30B model with alpa, It runs well.
**Please describe the expected behavior**
I want to run the OPT_66B with alpa
**System information and environment**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Ubuntu 20.04
Python version: 3.8
CUDA version:11.3
NCCL version: 2.9.6
cupy version: cupy-cuda113
GPU model and memory: RTX 3090 (single node)
Alpa version: github@main
TensorFlow version: 2.10.0
JAX version:0.3.22

**To Reproduce**
1. run the run_clm_flax.py in alpa/example/opt_finetune with revising the model name as (--model_name_or_path="facebook/opt-66b" \)
2. --per_device_train_batch_size="1"
    --num_micro_batches="1"

**Comment by zhisbug** [comment]
@cksmll The peak RAM usage estimation (66B x 2 bytes x 2 = 264GB) is for weight conversion. It seems you have done weight conversion and started the fine-tuning job. So the estimation 264GB is not relevant. Running fine-tuning requires more GPU memory. Could you try to run inference only here: https://github.com/alpa-projects/alpa/blob/main/examples/llm_serving/textgen.py

**Comment by merrymercy** [comment]
When you run fine-tuning, the weight initialization happens on CPU, which can take a lot of CPU RAM before you see any GPU activity.
Could you try to follow this example to parallelize the weight initialize stage on multiple GPUs? Running fine-tuning also needs significantly more memory than running inference.
https://github.com/alpa-projects/alpa/blob/4a281c62a7678e43f03273ccd65494480c413b92/tests/runtime/test_create_state.py#L68

**Comment by merrymercy** [comment]
close this one and move the discussion to #822
