### ISSUE TITLE
[BUG] Setting preallocation to false not work

### ISSUE THREAD

**Issue by frankxyy** [alpa-projects/alpa#817]
I set env variable `XLA_PYTHON_CLIENT_PREALLOCATE` to 1 but the gpu memory usage donot change.

**Comment by zhisbug** [comment]
this env var controls how XLA pre-allocates the GPU (statically) memory when it is launched. It does not affect runtime memory usage.

**Comment by zhisbug** [comment]
it is a float value, e.g., 0.75 / 0.5 / 1.0

**Comment by frankxyy** [comment]
> allocates

hi @zhisbug , according to the jax documentation (https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html) ,  
![image](https://user-images.githubusercontent.com/6971044/208366593-a79e5179-9fcf-4b3f-9af0-0f2ccd26ed0c.png)

XLA_PYTHON_CLIENT_MEM_FRACTION is a float while XLA_PYTHON_CLIENT_PREALLOCATE is a bool.

**Comment by merrymercy** [comment]
Hi, you should forward these env vars to workers by adding some code here, similar to what we did for `XLA_PYTHON_CLIENT_MEM_FRACTION`
https://github.com/alpa-projects/alpa/blob/4a281c62a7678e43f03273ccd65494480c413b92/alpa/device_mesh.py#L1058-L1074

Would you mind submitting a PR?

**Comment by frankxyy** [comment]
@merrymercy  OK, get it
