### ISSUE TITLE
[Discussion]What's the difference and relationship of `alpa` and `DTensor`?

### ISSUE THREAD

**Issue by GHGmc2** [alpa-projects/alpa#821]
Hi, I'm new to alpa, may I know what's the difference and relationship of `alpa` and TensorFlow `DTensor`?

- [Alpa: Automated Model-Parallel Deep Learning](https://ai.googleblog.com/2022/05/alpa-automated-model-parallel-deep.html)
- [TensorFlow DTensor](https://www.tensorflow.org/guide/dtensor_overview)

Thanks!

**Comment by GHGmc2** [comment]
@zhisbug Thanks for the explanation, seems alpa is the superset of DTensor?

What I concern about is the character of alpa after DTensor is formally and fully supported(it's under experimental state for now), will alpa be a third-party extension or a native solution at that point?

**Comment by zhisbug** [comment]
@GHGmc2 

Thanks for the raising the concern.
We do not have any plan to support DTensor. Alpa mainly works for JAX frontend. DTensor is TensorFlow frontend data structure. We do not have any plan to provide a TF-based interface in a short term (though one can make it work with TensorFlow by adding some wrapping on top of XLA)

**Comment by GHGmc2** [comment]
@zhisbug Hi, I noticed that TensorFlow had integrated part of alpa into it, will alpa be part of TensorFlow in the future? https://github.com/tensorflow/tensorflow/commit/6b5148da62350f08fabd8091e9ca13ac5609a963

**Comment by zhisbug** [comment]
@GHGmc2 Like you said, some parts of Alpa have been upstreamed to XLA and openXLA. The authors are @zhuohan123 and some of our Google internal collaborators and user; for that part of code (like the one you mentioned) we are trying to main just one version in the longer run; But Alpa has large chunks of code/features which will stay at Alpa repo and be developed by Alpa community.

**Comment by GHGmc2** [comment]
@zhisbug Thanks for the info.
