### ISSUE TITLE
Why is the throughput continuing increasing with the process of training?

### ISSUE THREAD

**Issue by frankxyy** [alpa-projects/alpa#823]
I print the throughput (samples / sec) after every step and find that the throughput is increasing with the process of training, from 200 samples/s to 300 samples/s. Why does this happen?

**Comment by merrymercy** [comment]
The first iteration counts the compilation time, so it is significantly slower. The first few iterations are used for warmup, they are typically skipped for benchmark purposes.
In some scripts, compilation and checkpointing are counted as iteration time, you should carefully skip them for benchmark purposes.

**Comment by frankxyy** [comment]
@merrymercy get it, thank you
