### ISSUE TITLE
What is alpa's modification to the original jaxlib?

### ISSUE THREAD

**Issue by frankxyy** [alpa-projects/alpa#831]
Hi, I want to know about the alpa's modification to the original jaxlib source code. This is for the purpose of bettering understand the implementation of alpa and making it easier to do further developing on the alpa code base.

**Comment by zhisbug** [comment]
@frankxyy you can learn it by reading: 

https://alpa.ai/developer/developer_guide.html
https://alpa.ai/architecture/alpa_compiler_walk_through.html#auto-sharding
https://alpa.ai/architecture/intra_op_solver.html
