### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by davidmosesbass** [alpa-projects/alpa#833]
**Please describe the bug**

**Please describe the expected behavior**

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker):
- Python version:
- CUDA version:
- NCCL version:
- cupy version:
- GPU model and memory:
- Alpa version:
- TensorFlow version:
- JAX version:

**To Reproduce**
1.
2.
3.

**Screenshots**

**Code snippet to reproduce the problem**

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by merrymercy** [comment]
Could you describe your issues?
