### ISSUE TITLE
[PERF] Move cached property out of `DistributedArray`

### ISSUE THREAD

**Issue by ZYHowell** [alpa-projects/alpa#837]
Background
---
To manage a tensor distributed on a device mesh, we use `DistributedArray` to represent this concept on the driver side. The class implements apis to load, save, and retrieve data from devices to the driver. Because the tensor is sharded on the device mesh, the `DistributedArray` should know how to get all parts of the data, see [this property](https://github.com/alpa-projects/alpa/blob/main/alpa/device_mesh.py#L1638-L1643). The `DistributedArray` is read-only, so we cache the property.
However, we found `DistributedArray` exceptionally light. In each iteration(a.k.a. generating a token), the driver needs to get a tiny tensor from devices. Although the tensor's sharding spec is the same for each iteration, the `DistributedArray` object differs, and the property needs to be repeatedly computed for each iter.
In this issue, we want to move computing `one_replica_buffer_ids` from `DistributedArray` to `PhysicalDeviceMesh` or even just a util function, because once the mesh shape and sharding spec are kept, we can know how to get and assemble shards to cover the whole tensor.

TODO
---
- [ ] Move `compute_one_replica_ids` to `PhysicalDeviceMesh` or `util`. It only uses sharding spec and mesh shape as inputs, regardless of which array it computes;
- [ ] Support `ReplicatedDistributedArray`.

**Comment by Vatshank** [comment]
Hey @ZYHowell, I'd like to take a stab at fixing this issue unless someone else is already working on it. 

Looking at a couple of tests (`runtime/test_device_mesh.py` and `pipeline_parallel/test_mlp.py` mainly) and setting breakpoints, I do see a lot of calls to the `compute_one_replica_ids` but I wasn't sure if that's what you had in mind for this issue. Could you point me to the bit in code that cause the repeated calls you mentioned above?

>  In each iteration(a.k.a. generating a token), the driver needs to get a tiny tensor from devices.

**Comment by akhmedsakip** [comment]
Hello @Vatshank,

Thank you for asking if someone is working on the issue. I have been working on it for a couple of weeks, so would it be okay if I continue? I am very sorry for not commenting here earlier for an official assignment.

Regarding your questions, I will try my best to answer them in a few days.

**Comment by akhmedsakip** [comment]
> Hey @ZYHowell, I'd like to take a stab at fixing this issue unless someone else is already working on it.
> 
> Looking at a couple of tests (`runtime/test_device_mesh.py` and `pipeline_parallel/test_mlp.py` mainly) and setting breakpoints, I do see a lot of calls to the `compute_one_replica_ids` but I wasn't sure if that's what you had in mind for this issue. Could you point me to the bit in code that causes the repeated calls you mentioned above?
> 
> > In each iteration(a.k.a. generating a token), the driver needs to get a tiny tensor from devices.
> 
> And to make sure I understand this correctly - we are able to move this property out of `DistributedArray` because given a fixed `physical_mesh` and a fixed `sharding_spec`, any calls to shard an array using [`shard_args_to_arrays`](https://github.com/alpa-projects/alpa/blob/main/alpa/device_mesh.py#L1317) will shard the arrays similarly and hence we do not need to recompute the `one_replica_buffer_ids` for this given (`physical_mesh`, `sharding_spec`) pair every time [`_value`](https://github.com/alpa-projects/alpa/blob/main/alpa/device_mesh.py#L1649) is called?

Hello @Vatshank,

Thank you for asking if someone is working on the issue. I have been working on it for a couple of weeks, so would it be okay if I continue? I am very sorry for not commenting here earlier for an official assignment.

Regarding your questions, I will try my best to answer them in a few days.
