### ISSUE TITLE
[FEATURE] OPT-175B scheduling to favor cached logprobs requests

### ISSUE THREAD

**Issue by JubilantJerry** [alpa-projects/alpa#853]
This is a proposed feature.

## Background

The `logprobs` endpoint exists so clients can implement their own sampling strategy for decoding. This means the user uses `logprobs` once per token of their output, and that the hidden layer outputs needed for self-attention are shared and mutated across a whole chain of RPC requests (which is why there is a cache).

In the current design of `llm_serving`, the cache has a fixed and pretty small size, and if `logprobs` is used after the cached hidden layer outputs are evicted, a lot of computation (i.e. the sum of all the previous requests in the chain) is repeated. Having a cache is probably unavoidable, but to minimize cache misses it's better to keep the working set small, meaning that we ideally want to complete the whole request chain associated with a single cache entry before starting a new request chain. Otherwise, if several users are concurrently trying to use `logprobs` for decoding, their cache entries evict each other and the server experiences thrashing.

## Method
I suggest having a higher scheduling priority for `logprobs` requests that use existing cache entries. This can be an easy extension of the scheduling mechanism proposed in #700. To keep the system fair, we can use this design:

- The first `logprobs` request has standard priority.
- If a `logprobs` request's `cache_id` is found in the cache, and the first request corresponding to this `cache_id` is not more than `LOGPROBS_PRIORITY_TIME_LIMIT_S` seconds old, the request is scheduled with high priority so that it becomes the next task to run.
- If the prompt of a cached logprobs request is not precisely what was used last time for the cache + one more token, return an error to the user and evict the cache entry.

Under these conditions, each request chain is finite length and the computational work for the whole chain is about the same as a single generation task of the same sequence length. The scheduling of the whole chain of tasks is handled simply with the first task in the chain. The way we currently implement `logprobs`, the output is gibberish if the prompts don't extend by 1 token each call, so we should call that out - this check (and the subsequent cache eviction) is necessary to ensure the finite chain length anyway.

Having a time limit on the recency of the first request in the chain limits the maximum latency on interactive requests, though the worst case can only happen if almost all requests are `logprobs` of long sequence lengths, and the interactive queue was empty before the new interactive request came in. The latency will be the lesser between the processing time for `cache_size` maximum size `logprobs` requests, and `LOGPROBS_PRIORITY_TIME_LIMIT_S` seconds.

**Comment by merrymercy** [comment]
closed by #870
