### ISSUE TITLE
Plans for PyTorch frontend weight sharing?

### ISSUE THREAD

**Issue by jaywonchung** [alpa-projects/alpa#859]
I was just wondering about what plans (e.g. target version, target dev time) the Alpa team has about supporting weight sharing for the PyTorch frontend.
If my understanding is correct, weight sharing is important because many, if not all, language models share the weights of the token embedding layer and the output token prediction layer.

Thanks a lot.

**Comment by merrymercy** [comment]
The support of the PyTorch frontend is paused. We welcome community contributions but do not have the capacity to do it by ourselves.
