### ISSUE TITLE
"Cannot connect to the server due to unknown errors." when hosting OPT-175B with launch_website.py

### ISSUE THREAD

**Issue by JingfengYang** [alpa-projects/alpa#861]
**Please describe the bug**
launch_model_worker.py and test_completions.py can successfully run with expected behavior.
But after running  `uvicorn launch_website:app --host 0.0.0.0 --port 12315` to launch website, it shows "Cannot connect to the server due to unknown errors. The server is probably under regular maintenance. Please come back later." when typing in prompts and clicking Generate button.

**Please describe the expected behavior**
The expected behavior should be returning generated texts when typing in prompts and clicking Generate button.

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker):
- Python version:
- CUDA version:
- NCCL version:
- cupy version:
- GPU model and memory:
- Alpa version:
- TensorFlow version:
- JAX version:

**To Reproduce**
1.
2.
3.

**Screenshots**
![image](https://user-images.githubusercontent.com/26218692/213400419-186957fc-d680-404c-872d-e406d45247a8.png)

**Code snippet to reproduce the problem**

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by JubilantJerry** [comment]
Could you open the developer console and see what got printed? Also, are you opening the browser on the same server that is running the backend, or are you using remote access?

**Comment by JingfengYang** [comment]
Hi there is no printed info from `launch_model_worker.py` console. Here is the printed info from `uvicorn launch_website:app --host 0.0.0.0 --port 12315` console: 
![image](https://user-images.githubusercontent.com/26218692/213517399-8e4db95e-13e6-4cd0-98d8-a1add5cfd0a1.png)

I run `launch_model_worker.py` and `uvicorn launch_website:app --host 0.0.0.0 --port 12315` in the same server, but open the browser with remote access. Remote access was successful with the first version of Alpa, where running only one script is enough to launch.

This is the command running `launch_model_worker.py`: `python3 launch_model_worker.py --model alpa/opt-175b --path /home/ec2-user/quic-efs/user/share/opt_alpa/opt_175b`. I think it works well because I test it with `test_completions.py` successfully. But it does not print any output when running `launch_model_worker.py` and using browser to send generate request.

**Comment by JingfengYang** [comment]
I see. That could be the reason. I'm sure that the browser only has access to port 12315 of remote server, but not 20001. Does this version of alpa requires browser to have access to both port 12315 and 20001?

**Comment by JingfengYang** [comment]
Is there anyway that only one port exposed to the remote end could work. Because it requires much more effort to expose more ports to have access on our side.

**Comment by JubilantJerry** [comment]
I'm not one of the devs, but I don't think that could work because the frontend and backend are separate services in the design they used. It's actually possible to directly use the backend via POST API. Plus, the backend probably needs to scale over a big cluster of GPU server blades while a small workstation could handle a lot of frontend requests, so the frontend and backend may even be different hostnames.

**Comment by merrymercy** [comment]
closed due to inactivity
