### ISSUE TITLE
Ask for the visualization of the partition strategy of Alpa on GPT-3

### ISSUE THREAD

**Issue by tntnnlrw** [alpa-projects/alpa#866]
**System information**
- Alpa version:0.2.2
- Are you willing to contribute it (Yes/No): No

**Describe the new feature and the current behavior/state**
A tool to quickly generate the visualization of the partition strategy of Alpa on GPT-3 like the Fig.13 in Alpa paper.
![image](https://user-images.githubusercontent.com/75306873/214010627-4c6bec73-ced8-491f-a20d-7f21458ba354.png)

**Will this change the current API? How?**
No
**Additional context**
Thanks a lot.

**Comment by zhisbug** [comment]
@tntnnlrw Hi, unfortunately, we do not have a tool. This was drawn manually by @ZYHowell on Powerpoint.
