### ISSUE TITLE
Need help installing requirements

### ISSUE THREAD

**Issue by altosaar** [alpa-projects/alpa#869]
**Please describe the bug**

When following the first step of the instructions to install the requirements, I am not sure whether the “alpa” library requires a GPU because cuda is mentioned, or whether I can run it on my Macbook Pro computer?

**Please describe the expected behavior**

Smooth installation.

**To Reproduce**
1. Go to documentation
2. Try the first step

**Comment by merrymercy** [comment]
Sorry, a GPU with CUDA is required
