### ISSUE TITLE
Can you provide convert OPT-xx weights into Alpa formats?

### ISSUE THREAD

**Issue by liguodongiot** [alpa-projects/alpa#890]
I find convert OPT-175B weights into Alpa formats on the [official website](https://alpa.ai/tutorials/opt_serving.html#convert-weights-format), but it can't convert OPT-(`125m~66b`) ，Can you provide convert OPT-(`125m~66b`) weights into Alpa formats?

<img width="658" alt="image" src="https://user-images.githubusercontent.com/13220186/222645934-c6697906-c514-4758-95e9-f1f84d3a333e.png">

**Comment by zhisbug** [comment]
@liguodongiot I have that, what's the best way to give to you?

**Comment by liguodongiot** [comment]
你好,我是李国冬，我已收到你的邮件，我会尽快给您回复。

**Comment by liguodongiot** [comment]
@zhisbug I want to convert opt 125-66b pytorch format to alpa format , Instead of the converted opt format。Can you provide the corresponding conversion code？

<img width="674" alt="image" src="https://user-images.githubusercontent.com/13220186/222884478-cfee79e1-c9cc-400b-805e-be607f8294c3.png">

Best wishes!

**Comment by merrymercy** [comment]
If you run these commands with opt 125M-66B, Alpa will automatically download and convert the weights
