### ISSUE TITLE
[Question] Introspecting Alpa's sharding/parallelization decision

### ISSUE THREAD

**Issue by jaywonchung** [alpa-projects/alpa#891]
Alpa has many parallelization methods like`PipeshardParallel`. Is there a generic way to understand the generated plan, i.e. how layers are split into pipeline stages each with how many GPUs, and how each layer is parallelized (intra-op parallelism dimension and degree)?

Currently Alpa prints out some text and numbers, but as someone who haven't read the codebase, it's difficult to understand terms such as logical vs physical mesh, sharding spec, etc. Also there is `alpa.parallel_plan`, but fields lack documentation, with many that I don't think are self-explanatory with their names and types (e.g. `pipeline_schedule: str`, `auto_sharding_solution: np.ndarray`, `auto_sharding_objective: int`).

Thanks.

**Comment by zhisbug** [comment]
@jaywonchung Everytime after compilation Alpa will dump some debugging info on disk. In those dumps you can find how pipelines are formed (inter-op plan) , how stages are communicated (cross-mesh resharding plan,) and how each stage is sharded (intra-op plan) by reading the several files in the dump.

**Comment by merrymercy** [comment]
See doc here https://alpa.ai/tutorials/perf_tuning_guide.html#inspect-the-parallelization-strategy
