### ISSUE TITLE
Why do not use the latest `jaxlib` and `jax`?

### ISSUE THREAD

**Issue by chaoming0625** [alpa-projects/alpa#911]
Dear all, thanks for your wonderful work! I found that using `alpa` needs to install ``jaxlib=0.3.22``. I am just curious about why do not use the latest `jaxlib` and `jax`? Thanks~

**Comment by jiaodong** [comment]
@chaoming0625 there's a rebase on the way. Alpa uses a fixes version of jax and jaxlib because the autosharding passes are implemented on a fork of gspmd which lives in jaxlib, that needs to be regularly rebased, we're looking for ways to further simplify this burden.

**Comment by chaoming0625** [comment]
@jiaodong So many thanks for your clarification! I am looking forward to the further update~
