### ISSUE TITLE
Specify Ray instance port

### ISSUE THREAD

**Issue by akhmedsakip** [alpa-projects/alpa#913]
**System information**
- Alpa version: 0.2.3
- Are you willing to contribute it (Yes/No): Probably not qualified

**Describe the new feature and the current behavior/state**
Currently, Apla is fixed to connecting to port 6379 of a Ray instance. This limits the number of users in a node with multiple GPUs to 1 (e.g., if there are 4 GPUs, 2 users cannot use 2 GPUs each). While it is possible to start a Ray instance listening on a different port, Alpa seems to use 6379 by default, but no 2 Ray instances can listen on the same port. Would it be possible to have this port specified in a configuration file or in the arguments, so that a 2nd user could start a Ray instance on a port different than 6379?

**Comment by gjoliver** [comment]
yeah, should be an easy change to make.
let me look into this and propose a quick PR.
thanks for the feedback!
