### ISSUE TITLE
PLS! why each device mesh's memory is always full?

### ISSUE THREAD

**Issue by KylinC** [alpa-projects/alpa#948]
run on two GPU: 4090(24G) and 2070(8G), test on llm_serving, opt-2.7b, I think it should take up about 5.4GB memory, but It takes 2070 7G/8G and 4090 22G/24G, I really want to know why. Thx.

**Comment by merrymercy** [comment]
https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html
https://github.com/alpa-projects/alpa/blob/852d632ab890bce4876bfcbc8f54313110e84d1d/alpa/global_env.py#L13-L15
