### ISSUE TITLE
Question abuot licence / usage

### ISSUE THREAD

**Issue by EnricoBeltramo** [alpa-projects/alpa#955]
**System information**
NA

**Describe the new feature and the current behavior/state**
Looking in your documentation looks that Alpha service can't be used in commercial application. But is possible to create custom applications infrastructure built on top of Alpha libraries for commercial use?

**Will this change the current API? How?**
No

**Describe alternatives you've considered**
Na

**Additional context**

**Comment by merrymercy** [comment]
yes. The code is under apache license so it allows commercial use
